// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/dto.dart';
import 'api/sdk.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  int dco_decode_CastedPrimitive_i_64(dynamic raw);

  @protected
  int dco_decode_CastedPrimitive_u_64(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AppLogLevelDto dco_decode_app_log_level_dto(dynamic raw);

  @protected
  AudioHashesDto dco_decode_audio_hashes_dto(dynamic raw);

  @protected
  AudioQualityDto dco_decode_audio_quality_dto(dynamic raw);

  @protected
  AuthStateDto dco_decode_auth_state_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  DeviceProfileDto dco_decode_box_autoadd_device_profile_dto(dynamic raw);

  @protected
  HeartRadioRequestDto dco_decode_box_autoadd_heart_radio_request_dto(
    dynamic raw,
  );

  @protected
  LyricDocumentDto dco_decode_box_autoadd_lyric_document_dto(dynamic raw);

  @protected
  PersonalFmRequestDto dco_decode_box_autoadd_personal_fm_request_dto(
    dynamic raw,
  );

  @protected
  PlaylistEditInputDto dco_decode_box_autoadd_playlist_edit_input_dto(
    dynamic raw,
  );

  @protected
  ResolvePlaybackRequestDto dco_decode_box_autoadd_resolve_playback_request_dto(
    dynamic raw,
  );

  @protected
  SearchRequestDto dco_decode_box_autoadd_search_request_dto(dynamic raw);

  @protected
  SongDto dco_decode_box_autoadd_song_dto(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BridgeError dco_decode_bridge_error(dynamic raw);

  @protected
  BridgeErrorKind dco_decode_bridge_error_kind(dynamic raw);

  @protected
  CloudPlaylistDto dco_decode_cloud_playlist_dto(dynamic raw);

  @protected
  CloudPlaylistPageDto dco_decode_cloud_playlist_page_dto(dynamic raw);

  @protected
  DeviceProfileDto dco_decode_device_profile_dto(dynamic raw);

  @protected
  HeartRadioRequestDto dco_decode_heart_radio_request_dto(dynamic raw);

  @protected
  HistoryPageDto dco_decode_history_page_dto(dynamic raw);

  @protected
  HistorySongDto dco_decode_history_song_dto(dynamic raw);

  @protected
  HistoryUploadItemDto dco_decode_history_upload_item_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<int> dco_decode_list_CastedPrimitive_u_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<CloudPlaylistDto> dco_decode_list_cloud_playlist_dto(dynamic raw);

  @protected
  List<HistorySongDto> dco_decode_list_history_song_dto(dynamic raw);

  @protected
  List<HistoryUploadItemDto> dco_decode_list_history_upload_item_dto(
    dynamic raw,
  );

  @protected
  List<LyricLineDto> dco_decode_list_lyric_line_dto(dynamic raw);

  @protected
  List<LyricWordDto> dco_decode_list_lyric_word_dto(dynamic raw);

  @protected
  List<PlaylistSearchHitDto> dco_decode_list_playlist_search_hit_dto(
    dynamic raw,
  );

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RecommendationHistoryItemDto>
  dco_decode_list_recommendation_history_item_dto(dynamic raw);

  @protected
  List<SongDto> dco_decode_list_song_dto(dynamic raw);

  @protected
  List<VipProductDto> dco_decode_list_vip_product_dto(dynamic raw);

  @protected
  LyricDocumentDto dco_decode_lyric_document_dto(dynamic raw);

  @protected
  LyricFetchDto dco_decode_lyric_fetch_dto(dynamic raw);

  @protected
  LyricFormatDto dco_decode_lyric_format_dto(dynamic raw);

  @protected
  LyricLineDto dco_decode_lyric_line_dto(dynamic raw);

  @protected
  LyricWordDto dco_decode_lyric_word_dto(dynamic raw);

  @protected
  int? dco_decode_opt_CastedPrimitive_i_64(dynamic raw);

  @protected
  int? dco_decode_opt_CastedPrimitive_u_64(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  SongDto? dco_decode_opt_box_autoadd_song_dto(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  PersonalFmActionDto dco_decode_personal_fm_action_dto(dynamic raw);

  @protected
  PersonalFmRequestDto dco_decode_personal_fm_request_dto(dynamic raw);

  @protected
  PlaybackResolutionDto dco_decode_playback_resolution_dto(dynamic raw);

  @protected
  PlaylistEditInputDto dco_decode_playlist_edit_input_dto(dynamic raw);

  @protected
  PlaylistMutationDto dco_decode_playlist_mutation_dto(dynamic raw);

  @protected
  PlaylistSearchHitDto dco_decode_playlist_search_hit_dto(dynamic raw);

  @protected
  PlaylistSearchPageDto dco_decode_playlist_search_page_dto(dynamic raw);

  @protected
  PlaylistTracksMutationDto dco_decode_playlist_tracks_mutation_dto(
    dynamic raw,
  );

  @protected
  RecommendationBatchDto dco_decode_recommendation_batch_dto(dynamic raw);

  @protected
  RecommendationHistoryActionDto dco_decode_recommendation_history_action_dto(
    dynamic raw,
  );

  @protected
  RecommendationHistoryItemDto dco_decode_recommendation_history_item_dto(
    dynamic raw,
  );

  @protected
  RecommendationReportAckDto dco_decode_recommendation_report_ack_dto(
    dynamic raw,
  );

  @protected
  ResolvePlaybackRequestDto dco_decode_resolve_playback_request_dto(
    dynamic raw,
  );

  @protected
  SearchRequestDto dco_decode_search_request_dto(dynamic raw);

  @protected
  SongDto dco_decode_song_dto(dynamic raw);

  @protected
  SongPageDto dco_decode_song_page_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UserProfileDto dco_decode_user_profile_dto(dynamic raw);

  @protected
  UserVipDto dco_decode_user_vip_dto(dynamic raw);

  @protected
  VipClaimResultDto dco_decode_vip_claim_result_dto(dynamic raw);

  @protected
  VipMonthRecordDto dco_decode_vip_month_record_dto(dynamic raw);

  @protected
  VipProductDto dco_decode_vip_product_dto(dynamic raw);

  @protected
  VipUpgradeResultDto dco_decode_vip_upgrade_result_dto(dynamic raw);

  @protected
  int sse_decode_CastedPrimitive_i_64(SseDeserializer deserializer);

  @protected
  int sse_decode_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AppLogLevelDto sse_decode_app_log_level_dto(SseDeserializer deserializer);

  @protected
  AudioHashesDto sse_decode_audio_hashes_dto(SseDeserializer deserializer);

  @protected
  AudioQualityDto sse_decode_audio_quality_dto(SseDeserializer deserializer);

  @protected
  AuthStateDto sse_decode_auth_state_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  DeviceProfileDto sse_decode_box_autoadd_device_profile_dto(
    SseDeserializer deserializer,
  );

  @protected
  HeartRadioRequestDto sse_decode_box_autoadd_heart_radio_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  LyricDocumentDto sse_decode_box_autoadd_lyric_document_dto(
    SseDeserializer deserializer,
  );

  @protected
  PersonalFmRequestDto sse_decode_box_autoadd_personal_fm_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  PlaylistEditInputDto sse_decode_box_autoadd_playlist_edit_input_dto(
    SseDeserializer deserializer,
  );

  @protected
  ResolvePlaybackRequestDto sse_decode_box_autoadd_resolve_playback_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  SearchRequestDto sse_decode_box_autoadd_search_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  SongDto sse_decode_box_autoadd_song_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BridgeError sse_decode_bridge_error(SseDeserializer deserializer);

  @protected
  BridgeErrorKind sse_decode_bridge_error_kind(SseDeserializer deserializer);

  @protected
  CloudPlaylistDto sse_decode_cloud_playlist_dto(SseDeserializer deserializer);

  @protected
  CloudPlaylistPageDto sse_decode_cloud_playlist_page_dto(
    SseDeserializer deserializer,
  );

  @protected
  DeviceProfileDto sse_decode_device_profile_dto(SseDeserializer deserializer);

  @protected
  HeartRadioRequestDto sse_decode_heart_radio_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  HistoryPageDto sse_decode_history_page_dto(SseDeserializer deserializer);

  @protected
  HistorySongDto sse_decode_history_song_dto(SseDeserializer deserializer);

  @protected
  HistoryUploadItemDto sse_decode_history_upload_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<CloudPlaylistDto> sse_decode_list_cloud_playlist_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<HistorySongDto> sse_decode_list_history_song_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<HistoryUploadItemDto> sse_decode_list_history_upload_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<LyricLineDto> sse_decode_list_lyric_line_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<LyricWordDto> sse_decode_list_lyric_word_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<PlaylistSearchHitDto> sse_decode_list_playlist_search_hit_dto(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RecommendationHistoryItemDto>
  sse_decode_list_recommendation_history_item_dto(SseDeserializer deserializer);

  @protected
  List<SongDto> sse_decode_list_song_dto(SseDeserializer deserializer);

  @protected
  List<VipProductDto> sse_decode_list_vip_product_dto(
    SseDeserializer deserializer,
  );

  @protected
  LyricDocumentDto sse_decode_lyric_document_dto(SseDeserializer deserializer);

  @protected
  LyricFetchDto sse_decode_lyric_fetch_dto(SseDeserializer deserializer);

  @protected
  LyricFormatDto sse_decode_lyric_format_dto(SseDeserializer deserializer);

  @protected
  LyricLineDto sse_decode_lyric_line_dto(SseDeserializer deserializer);

  @protected
  LyricWordDto sse_decode_lyric_word_dto(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_CastedPrimitive_i_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  SongDto? sse_decode_opt_box_autoadd_song_dto(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  PersonalFmActionDto sse_decode_personal_fm_action_dto(
    SseDeserializer deserializer,
  );

  @protected
  PersonalFmRequestDto sse_decode_personal_fm_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  PlaybackResolutionDto sse_decode_playback_resolution_dto(
    SseDeserializer deserializer,
  );

  @protected
  PlaylistEditInputDto sse_decode_playlist_edit_input_dto(
    SseDeserializer deserializer,
  );

  @protected
  PlaylistMutationDto sse_decode_playlist_mutation_dto(
    SseDeserializer deserializer,
  );

  @protected
  PlaylistSearchHitDto sse_decode_playlist_search_hit_dto(
    SseDeserializer deserializer,
  );

  @protected
  PlaylistSearchPageDto sse_decode_playlist_search_page_dto(
    SseDeserializer deserializer,
  );

  @protected
  PlaylistTracksMutationDto sse_decode_playlist_tracks_mutation_dto(
    SseDeserializer deserializer,
  );

  @protected
  RecommendationBatchDto sse_decode_recommendation_batch_dto(
    SseDeserializer deserializer,
  );

  @protected
  RecommendationHistoryActionDto sse_decode_recommendation_history_action_dto(
    SseDeserializer deserializer,
  );

  @protected
  RecommendationHistoryItemDto sse_decode_recommendation_history_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  RecommendationReportAckDto sse_decode_recommendation_report_ack_dto(
    SseDeserializer deserializer,
  );

  @protected
  ResolvePlaybackRequestDto sse_decode_resolve_playback_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  SearchRequestDto sse_decode_search_request_dto(SseDeserializer deserializer);

  @protected
  SongDto sse_decode_song_dto(SseDeserializer deserializer);

  @protected
  SongPageDto sse_decode_song_page_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UserProfileDto sse_decode_user_profile_dto(SseDeserializer deserializer);

  @protected
  UserVipDto sse_decode_user_vip_dto(SseDeserializer deserializer);

  @protected
  VipClaimResultDto sse_decode_vip_claim_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  VipMonthRecordDto sse_decode_vip_month_record_dto(
    SseDeserializer deserializer,
  );

  @protected
  VipProductDto sse_decode_vip_product_dto(SseDeserializer deserializer);

  @protected
  VipUpgradeResultDto sse_decode_vip_upgrade_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  void sse_encode_CastedPrimitive_i_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_CastedPrimitive_u_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_app_log_level_dto(
    AppLogLevelDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_audio_hashes_dto(
    AudioHashesDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_audio_quality_dto(
    AudioQualityDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_auth_state_dto(AuthStateDto self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_device_profile_dto(
    DeviceProfileDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_heart_radio_request_dto(
    HeartRadioRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_lyric_document_dto(
    LyricDocumentDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_personal_fm_request_dto(
    PersonalFmRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_playlist_edit_input_dto(
    PlaylistEditInputDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_resolve_playback_request_dto(
    ResolvePlaybackRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_search_request_dto(
    SearchRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_song_dto(SongDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_error(BridgeError self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_error_kind(
    BridgeErrorKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cloud_playlist_dto(
    CloudPlaylistDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cloud_playlist_page_dto(
    CloudPlaylistPageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_device_profile_dto(
    DeviceProfileDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_heart_radio_request_dto(
    HeartRadioRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_history_page_dto(
    HistoryPageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_history_song_dto(
    HistorySongDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_history_upload_item_dto(
    HistoryUploadItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_CastedPrimitive_u_64(
    List<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_cloud_playlist_dto(
    List<CloudPlaylistDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_history_song_dto(
    List<HistorySongDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_history_upload_item_dto(
    List<HistoryUploadItemDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_lyric_line_dto(
    List<LyricLineDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_lyric_word_dto(
    List<LyricWordDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_playlist_search_hit_dto(
    List<PlaylistSearchHitDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_recommendation_history_item_dto(
    List<RecommendationHistoryItemDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_song_dto(List<SongDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_vip_product_dto(
    List<VipProductDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_lyric_document_dto(
    LyricDocumentDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_lyric_fetch_dto(LyricFetchDto self, SseSerializer serializer);

  @protected
  void sse_encode_lyric_format_dto(
    LyricFormatDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_lyric_line_dto(LyricLineDto self, SseSerializer serializer);

  @protected
  void sse_encode_lyric_word_dto(LyricWordDto self, SseSerializer serializer);

  @protected
  void sse_encode_opt_CastedPrimitive_i_64(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_CastedPrimitive_u_64(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_song_dto(
    SongDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_personal_fm_action_dto(
    PersonalFmActionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_personal_fm_request_dto(
    PersonalFmRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_playback_resolution_dto(
    PlaybackResolutionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_playlist_edit_input_dto(
    PlaylistEditInputDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_playlist_mutation_dto(
    PlaylistMutationDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_playlist_search_hit_dto(
    PlaylistSearchHitDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_playlist_search_page_dto(
    PlaylistSearchPageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_playlist_tracks_mutation_dto(
    PlaylistTracksMutationDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_recommendation_batch_dto(
    RecommendationBatchDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_recommendation_history_action_dto(
    RecommendationHistoryActionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_recommendation_history_item_dto(
    RecommendationHistoryItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_recommendation_report_ack_dto(
    RecommendationReportAckDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_resolve_playback_request_dto(
    ResolvePlaybackRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_search_request_dto(
    SearchRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_song_dto(SongDto self, SseSerializer serializer);

  @protected
  void sse_encode_song_page_dto(SongPageDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_user_profile_dto(
    UserProfileDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_user_vip_dto(UserVipDto self, SseSerializer serializer);

  @protected
  void sse_encode_vip_claim_result_dto(
    VipClaimResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_vip_month_record_dto(
    VipMonthRecordDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_vip_product_dto(VipProductDto self, SseSerializer serializer);

  @protected
  void sse_encode_vip_upgrade_result_dto(
    VipUpgradeResultDto self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
