// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/sdk.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSdkInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -298028128;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'kugou_bridge',
        ioDirectory: 'native/kugou_bridge/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiSdkAddSongToPlaylist({
    required int listId,
    required SongDto song,
  });

  Future<PlaylistMutationDto> crateApiSdkCollectCloudPlaylist({
    required String globalCollectionId,
    int? ownerUserId,
    String? name,
  });

  Future<PlaylistMutationDto> crateApiSdkCreateCloudPlaylist({
    required String name,
    required bool private,
  });

  Future<void> crateApiSdkDeleteCloudPlaylist({
    required int listId,
    required bool collected,
  });

  Future<void> crateApiSdkEditCloudPlaylist({
    required PlaylistEditInputDto input,
  });

  Future<String> crateApiSdkExportSession();

  Future<AuthStateDto> crateApiSdkGetAuthState();

  Future<SongPageDto> crateApiSdkGetCloudHistory();

  Future<CloudPlaylistPageDto> crateApiSdkGetCloudPlaylists({
    required int page,
    required int pageSize,
  });

  Future<RecommendationDto> crateApiSdkGetEverydayRecommendations();

  Future<SongPageDto> crateApiSdkGetPlaylistTracks({
    required PlaylistTracksRequestDto request,
  });

  SdkCapabilitiesDto crateApiSdkGetSdkCapabilities();

  Future<UserProfileDto> crateApiSdkGetUserProfile();

  Future<UserVipDto> crateApiSdkGetUserVip();

  Future<void> crateApiSdkImportSession({required String value});

  Future<void> crateApiSdkInitApp();

  Future<SdkCapabilitiesDto> crateApiSdkInitializeSdk();

  Future<SmsLoginResultDto> crateApiSdkLoginBySms({
    required String mobile,
    required String code,
  });

  Future<AuthStateDto> crateApiSdkLogout();

  Future<AuthStateDto> crateApiSdkRefreshLogin();

  Future<AuthStateDto> crateApiSdkRegisterDevice();

  Future<void> crateApiSdkRemoveSongFromPlaylist({
    required int listId,
    required int fileId,
  });

  Future<PlaybackResolutionDto> crateApiSdkResolvePlayback({
    required ResolvePlaybackRequestDto request,
  });

  Future<PlaylistSearchPageDto> crateApiSdkSearchPlaylists({
    required SearchRequestDto request,
  });

  Future<SongPageDto> crateApiSdkSearchSongs({
    required SearchRequestDto request,
  });

  Future<void> crateApiSdkSendSmsCode({required String mobile});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiSdkAddSongToPlaylist({
    required int listId,
    required SongDto song,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_CastedPrimitive_u_64(listId, serializer);
          sse_encode_box_autoadd_song_dto(song, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSdkAddSongToPlaylistConstMeta,
        argValues: [listId, song],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSdkAddSongToPlaylistConstMeta =>
      const TaskConstMeta(
        debugName: "add_song_to_playlist",
        argNames: ["listId", "song"],
      );

  @override
  Future<PlaylistMutationDto> crateApiSdkCollectCloudPlaylist({
    required String globalCollectionId,
    int? ownerUserId,
    String? name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(globalCollectionId, serializer);
          sse_encode_opt_CastedPrimitive_u_64(ownerUserId, serializer);
          sse_encode_opt_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_playlist_mutation_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSdkCollectCloudPlaylistConstMeta,
        argValues: [globalCollectionId, ownerUserId, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSdkCollectCloudPlaylistConstMeta =>
      const TaskConstMeta(
        debugName: "collect_cloud_playlist",
        argNames: ["globalCollectionId", "ownerUserId", "name"],
      );

  @override
  Future<PlaylistMutationDto> crateApiSdkCreateCloudPlaylist({
    required String name,
    required bool private,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_bool(private, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_playlist_mutation_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSdkCreateCloudPlaylistConstMeta,
        argValues: [name, private],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSdkCreateCloudPlaylistConstMeta =>
      const TaskConstMeta(
        debugName: "create_cloud_playlist",
        argNames: ["name", "private"],
      );

  @override
  Future<void> crateApiSdkDeleteCloudPlaylist({
    required int listId,
    required bool collected,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_CastedPrimitive_u_64(listId, serializer);
          sse_encode_bool(collected, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSdkDeleteCloudPlaylistConstMeta,
        argValues: [listId, collected],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSdkDeleteCloudPlaylistConstMeta =>
      const TaskConstMeta(
        debugName: "delete_cloud_playlist",
        argNames: ["listId", "collected"],
      );

  @override
  Future<void> crateApiSdkEditCloudPlaylist({
    required PlaylistEditInputDto input,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_playlist_edit_input_dto(input, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSdkEditCloudPlaylistConstMeta,
        argValues: [input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSdkEditCloudPlaylistConstMeta =>
      const TaskConstMeta(
        debugName: "edit_cloud_playlist",
        argNames: ["input"],
      );

  @override
  Future<String> crateApiSdkExportSession() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSdkExportSessionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSdkExportSessionConstMeta =>
      const TaskConstMeta(debugName: "export_session", argNames: []);

  @override
  Future<AuthStateDto> crateApiSdkGetAuthState() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_auth_state_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSdkGetAuthStateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSdkGetAuthStateConstMeta =>
      const TaskConstMeta(debugName: "get_auth_state", argNames: []);

  @override
  Future<SongPageDto> crateApiSdkGetCloudHistory() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_song_page_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSdkGetCloudHistoryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSdkGetCloudHistoryConstMeta =>
      const TaskConstMeta(debugName: "get_cloud_history", argNames: []);

  @override
  Future<CloudPlaylistPageDto> crateApiSdkGetCloudPlaylists({
    required int page,
    required int pageSize,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(page, serializer);
          sse_encode_u_32(pageSize, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_cloud_playlist_page_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSdkGetCloudPlaylistsConstMeta,
        argValues: [page, pageSize],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSdkGetCloudPlaylistsConstMeta =>
      const TaskConstMeta(
        debugName: "get_cloud_playlists",
        argNames: ["page", "pageSize"],
      );

  @override
  Future<RecommendationDto> crateApiSdkGetEverydayRecommendations() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_recommendation_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSdkGetEverydayRecommendationsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSdkGetEverydayRecommendationsConstMeta =>
      const TaskConstMeta(
        debugName: "get_everyday_recommendations",
        argNames: [],
      );

  @override
  Future<SongPageDto> crateApiSdkGetPlaylistTracks({
    required PlaylistTracksRequestDto request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_playlist_tracks_request_dto(
            request,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_song_page_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSdkGetPlaylistTracksConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSdkGetPlaylistTracksConstMeta =>
      const TaskConstMeta(
        debugName: "get_playlist_tracks",
        argNames: ["request"],
      );

  @override
  SdkCapabilitiesDto crateApiSdkGetSdkCapabilities() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sdk_capabilities_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSdkGetSdkCapabilitiesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSdkGetSdkCapabilitiesConstMeta =>
      const TaskConstMeta(debugName: "get_sdk_capabilities", argNames: []);

  @override
  Future<UserProfileDto> crateApiSdkGetUserProfile() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_user_profile_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSdkGetUserProfileConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSdkGetUserProfileConstMeta =>
      const TaskConstMeta(debugName: "get_user_profile", argNames: []);

  @override
  Future<UserVipDto> crateApiSdkGetUserVip() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_user_vip_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSdkGetUserVipConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSdkGetUserVipConstMeta =>
      const TaskConstMeta(debugName: "get_user_vip", argNames: []);

  @override
  Future<void> crateApiSdkImportSession({required String value}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(value, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSdkImportSessionConstMeta,
        argValues: [value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSdkImportSessionConstMeta =>
      const TaskConstMeta(debugName: "import_session", argNames: ["value"]);

  @override
  Future<void> crateApiSdkInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSdkInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSdkInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<SdkCapabilitiesDto> crateApiSdkInitializeSdk() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sdk_capabilities_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSdkInitializeSdkConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSdkInitializeSdkConstMeta =>
      const TaskConstMeta(debugName: "initialize_sdk", argNames: []);

  @override
  Future<SmsLoginResultDto> crateApiSdkLoginBySms({
    required String mobile,
    required String code,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mobile, serializer);
          sse_encode_String(code, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sms_login_result_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSdkLoginBySmsConstMeta,
        argValues: [mobile, code],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSdkLoginBySmsConstMeta => const TaskConstMeta(
    debugName: "login_by_sms",
    argNames: ["mobile", "code"],
  );

  @override
  Future<AuthStateDto> crateApiSdkLogout() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_auth_state_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSdkLogoutConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSdkLogoutConstMeta =>
      const TaskConstMeta(debugName: "logout", argNames: []);

  @override
  Future<AuthStateDto> crateApiSdkRefreshLogin() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_auth_state_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSdkRefreshLoginConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSdkRefreshLoginConstMeta =>
      const TaskConstMeta(debugName: "refresh_login", argNames: []);

  @override
  Future<AuthStateDto> crateApiSdkRegisterDevice() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_auth_state_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSdkRegisterDeviceConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSdkRegisterDeviceConstMeta =>
      const TaskConstMeta(debugName: "register_device", argNames: []);

  @override
  Future<void> crateApiSdkRemoveSongFromPlaylist({
    required int listId,
    required int fileId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_CastedPrimitive_u_64(listId, serializer);
          sse_encode_CastedPrimitive_u_64(fileId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSdkRemoveSongFromPlaylistConstMeta,
        argValues: [listId, fileId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSdkRemoveSongFromPlaylistConstMeta =>
      const TaskConstMeta(
        debugName: "remove_song_from_playlist",
        argNames: ["listId", "fileId"],
      );

  @override
  Future<PlaybackResolutionDto> crateApiSdkResolvePlayback({
    required ResolvePlaybackRequestDto request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_resolve_playback_request_dto(
            request,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_playback_resolution_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSdkResolvePlaybackConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSdkResolvePlaybackConstMeta =>
      const TaskConstMeta(debugName: "resolve_playback", argNames: ["request"]);

  @override
  Future<PlaylistSearchPageDto> crateApiSdkSearchPlaylists({
    required SearchRequestDto request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_search_request_dto(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_playlist_search_page_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSdkSearchPlaylistsConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSdkSearchPlaylistsConstMeta =>
      const TaskConstMeta(debugName: "search_playlists", argNames: ["request"]);

  @override
  Future<SongPageDto> crateApiSdkSearchSongs({
    required SearchRequestDto request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_search_request_dto(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_song_page_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSdkSearchSongsConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSdkSearchSongsConstMeta =>
      const TaskConstMeta(debugName: "search_songs", argNames: ["request"]);

  @override
  Future<void> crateApiSdkSendSmsCode({required String mobile}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mobile, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSdkSendSmsCodeConstMeta,
        argValues: [mobile],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSdkSendSmsCodeConstMeta =>
      const TaskConstMeta(debugName: "send_sms_code", argNames: ["mobile"]);

  @protected
  int dco_decode_CastedPrimitive_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError(
      'Not implemented in this codec, please use the other one',
    );
  }

  @protected
  int dco_decode_CastedPrimitive_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError(
      'Not implemented in this codec, please use the other one',
    );
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AudioHashesDto dco_decode_audio_hashes_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return AudioHashesDto(
      standard: dco_decode_opt_String(arr[0]),
      high: dco_decode_opt_String(arr[1]),
      flac: dco_decode_opt_String(arr[2]),
      hiRes: dco_decode_opt_String(arr[3]),
      superHash: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  AudioQualityDto dco_decode_audio_quality_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AudioQualityDto.values[raw as int];
  }

  @protected
  AuthStateDto dco_decode_auth_state_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return AuthStateDto(
      authenticated: dco_decode_bool(arr[0]),
      userId: dco_decode_opt_CastedPrimitive_u_64(arr[1]),
      vipType: dco_decode_opt_box_autoadd_u_32(arr[2]),
      fingerprintRegistered: dco_decode_bool(arr[3]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlaylistEditInputDto dco_decode_box_autoadd_playlist_edit_input_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_playlist_edit_input_dto(raw);
  }

  @protected
  PlaylistTracksRequestDto dco_decode_box_autoadd_playlist_tracks_request_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_playlist_tracks_request_dto(raw);
  }

  @protected
  ResolvePlaybackRequestDto dco_decode_box_autoadd_resolve_playback_request_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_resolve_playback_request_dto(raw);
  }

  @protected
  SearchRequestDto dco_decode_box_autoadd_search_request_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_search_request_dto(raw);
  }

  @protected
  SongDto dco_decode_box_autoadd_song_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_song_dto(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BridgeError dco_decode_bridge_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return BridgeError(
      kind: dco_decode_bridge_error_kind(arr[0]),
      message: dco_decode_String(arr[1]),
      code: dco_decode_opt_CastedPrimitive_i_64(arr[2]),
      retryable: dco_decode_bool(arr[3]),
    );
  }

  @protected
  BridgeErrorKind dco_decode_bridge_error_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BridgeErrorKind.values[raw as int];
  }

  @protected
  CloudPlaylistDto dco_decode_cloud_playlist_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return CloudPlaylistDto(
      listId: dco_decode_opt_CastedPrimitive_u_64(arr[0]),
      globalCollectionId: dco_decode_opt_String(arr[1]),
      name: dco_decode_String(arr[2]),
      intro: dco_decode_opt_String(arr[3]),
      artworkUrl: dco_decode_opt_String(arr[4]),
      count: dco_decode_opt_CastedPrimitive_u_64(arr[5]),
      listType: dco_decode_opt_box_autoadd_u_32(arr[6]),
      creatorUserId: dco_decode_opt_CastedPrimitive_u_64(arr[7]),
      creatorName: dco_decode_opt_String(arr[8]),
      isPrivate: dco_decode_bool(arr[9]),
      isMyFavorite: dco_decode_bool(arr[10]),
      isDefaultCollect: dco_decode_bool(arr[11]),
      tags: dco_decode_opt_String(arr[12]),
    );
  }

  @protected
  CloudPlaylistPageDto dco_decode_cloud_playlist_page_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return CloudPlaylistPageDto(
      items: dco_decode_list_cloud_playlist_dto(arr[0]),
      page: dco_decode_u_32(arr[1]),
      pageSize: dco_decode_u_32(arr[2]),
      total: dco_decode_opt_CastedPrimitive_u_64(arr[3]),
      totalVersion: dco_decode_opt_CastedPrimitive_u_64(arr[4]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<CloudPlaylistDto> dco_decode_list_cloud_playlist_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_cloud_playlist_dto).toList();
  }

  @protected
  List<PlaylistSearchHitDto> dco_decode_list_playlist_search_hit_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_playlist_search_hit_dto)
        .toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SongDto> dco_decode_list_song_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_song_dto).toList();
  }

  @protected
  int? dco_decode_opt_CastedPrimitive_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_CastedPrimitive_i_64(raw);
  }

  @protected
  int? dco_decode_opt_CastedPrimitive_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_CastedPrimitive_u_64(raw);
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bool(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  PlaybackResolutionDto dco_decode_playback_resolution_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return PlaybackResolutionDto_Playable(
          url: dco_decode_String(raw[1]),
          bitRate: dco_decode_opt_CastedPrimitive_u_64(raw[2]),
          durationSecs: dco_decode_opt_CastedPrimitive_u_64(raw[3]),
        );
      case 1:
        return PlaybackResolutionDto_Preview(
          url: dco_decode_String(raw[1]),
          endMs: dco_decode_opt_CastedPrimitive_u_64(raw[2]),
          bitRate: dco_decode_opt_CastedPrimitive_u_64(raw[3]),
          durationSecs: dco_decode_opt_CastedPrimitive_u_64(raw[4]),
        );
      case 2:
        return PlaybackResolutionDto_Denied(
          status: dco_decode_opt_CastedPrimitive_i_64(raw[1]),
          failProcess: dco_decode_opt_CastedPrimitive_i_64(raw[2]),
        );
      case 3:
        return PlaybackResolutionDto_Unavailable();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  PlaylistEditInputDto dco_decode_playlist_edit_input_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return PlaylistEditInputDto(
      listId: dco_decode_CastedPrimitive_u_64(arr[0]),
      name: dco_decode_opt_String(arr[1]),
      private: dco_decode_opt_box_autoadd_bool(arr[2]),
      intro: dco_decode_opt_String(arr[3]),
      tags: dco_decode_opt_String(arr[4]),
      totalVersion: dco_decode_opt_CastedPrimitive_u_64(arr[5]),
    );
  }

  @protected
  PlaylistMutationDto dco_decode_playlist_mutation_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return PlaylistMutationDto(
      listId: dco_decode_opt_CastedPrimitive_u_64(arr[0]),
      globalCollectionId: dco_decode_opt_String(arr[1]),
      name: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  PlaylistSearchHitDto dco_decode_playlist_search_hit_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return PlaylistSearchHitDto(
      specialId: dco_decode_opt_CastedPrimitive_u_64(arr[0]),
      globalCollectionId: dco_decode_opt_String(arr[1]),
      name: dco_decode_String(arr[2]),
      intro: dco_decode_opt_String(arr[3]),
      artworkUrl: dco_decode_opt_String(arr[4]),
      songCount: dco_decode_opt_CastedPrimitive_u_64(arr[5]),
      playCount: dco_decode_opt_CastedPrimitive_u_64(arr[6]),
      collectCount: dco_decode_opt_CastedPrimitive_u_64(arr[7]),
      creatorName: dco_decode_opt_String(arr[8]),
      creatorUserId: dco_decode_opt_CastedPrimitive_u_64(arr[9]),
      tags: dco_decode_opt_String(arr[10]),
    );
  }

  @protected
  PlaylistSearchPageDto dco_decode_playlist_search_page_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PlaylistSearchPageDto(
      items: dco_decode_list_playlist_search_hit_dto(arr[0]),
      page: dco_decode_u_32(arr[1]),
      pageSize: dco_decode_u_32(arr[2]),
      total: dco_decode_opt_CastedPrimitive_u_64(arr[3]),
    );
  }

  @protected
  PlaylistTracksRequestDto dco_decode_playlist_tracks_request_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return PlaylistTracksRequestDto(
      listId: dco_decode_opt_CastedPrimitive_u_64(arr[0]),
      globalCollectionId: dco_decode_opt_String(arr[1]),
      owned: dco_decode_bool(arr[2]),
      page: dco_decode_u_32(arr[3]),
      pageSize: dco_decode_u_32(arr[4]),
    );
  }

  @protected
  RecommendationDto dco_decode_recommendation_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return RecommendationDto(
      title: dco_decode_String(arr[0]),
      subtitle: dco_decode_opt_String(arr[1]),
      artworkUrl: dco_decode_opt_String(arr[2]),
      creationDate: dco_decode_opt_String(arr[3]),
      songs: dco_decode_list_song_dto(arr[4]),
    );
  }

  @protected
  ResolvePlaybackRequestDto dco_decode_resolve_playback_request_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ResolvePlaybackRequestDto(
      song: dco_decode_song_dto(arr[0]),
      quality: dco_decode_audio_quality_dto(arr[1]),
      freePreview: dco_decode_bool(arr[2]),
    );
  }

  @protected
  SdkCapabilitiesDto dco_decode_sdk_capabilities_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return SdkCapabilitiesDto(
      platform: dco_decode_String(arr[0]),
      songSearch: dco_decode_bool(arr[1]),
      playlistSearch: dco_decode_bool(arr[2]),
      dailyRecommendation: dco_decode_bool(arr[3]),
      smsAuth: dco_decode_bool(arr[4]),
      cloudLibrary: dco_decode_bool(arr[5]),
      playlistMutations: dco_decode_bool(arr[6]),
    );
  }

  @protected
  SearchRequestDto dco_decode_search_request_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SearchRequestDto(
      keyword: dco_decode_String(arr[0]),
      page: dco_decode_u_32(arr[1]),
      pageSize: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  SmsLoginResultDto dco_decode_sms_login_result_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SmsLoginResultDto(
      auth: dco_decode_auth_state_dto(arr[0]),
      fingerprintWarning: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  SongDto dco_decode_song_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return SongDto(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      artist: dco_decode_opt_String(arr[2]),
      album: dco_decode_opt_String(arr[3]),
      durationSecs: dco_decode_opt_CastedPrimitive_u_64(arr[4]),
      artworkUrl: dco_decode_opt_String(arr[5]),
      privilege: dco_decode_opt_CastedPrimitive_i_64(arr[6]),
      albumId: dco_decode_opt_CastedPrimitive_u_64(arr[7]),
      mixSongId: dco_decode_opt_CastedPrimitive_u_64(arr[8]),
      fileId: dco_decode_opt_CastedPrimitive_u_64(arr[9]),
      hashes: dco_decode_audio_hashes_dto(arr[10]),
    );
  }

  @protected
  SongPageDto dco_decode_song_page_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SongPageDto(
      items: dco_decode_list_song_dto(arr[0]),
      page: dco_decode_u_32(arr[1]),
      pageSize: dco_decode_u_32(arr[2]),
      total: dco_decode_opt_CastedPrimitive_u_64(arr[3]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  UserProfileDto dco_decode_user_profile_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return UserProfileDto(
      userId: dco_decode_opt_CastedPrimitive_u_64(arr[0]),
      displayName: dco_decode_String(arr[1]),
      username: dco_decode_opt_String(arr[2]),
      avatarUrl: dco_decode_opt_String(arr[3]),
      gender: dco_decode_opt_CastedPrimitive_i_64(arr[4]),
      birthday: dco_decode_opt_String(arr[5]),
      city: dco_decode_opt_String(arr[6]),
      province: dco_decode_opt_String(arr[7]),
      signature: dco_decode_opt_String(arr[8]),
      followingCount: dco_decode_opt_CastedPrimitive_u_64(arr[9]),
      fanCount: dco_decode_opt_CastedPrimitive_u_64(arr[10]),
      visitorCount: dco_decode_opt_CastedPrimitive_u_64(arr[11]),
    );
  }

  @protected
  UserVipDto dco_decode_user_vip_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return UserVipDto(
      vipType: dco_decode_opt_CastedPrimitive_i_64(arr[0]),
      musicPackageType: dco_decode_opt_CastedPrimitive_i_64(arr[1]),
      yearlyType: dco_decode_opt_CastedPrimitive_i_64(arr[2]),
      vipEndTime: dco_decode_opt_String(arr[3]),
      musicEndTime: dco_decode_opt_String(arr[4]),
      yearlyEndTime: dco_decode_opt_String(arr[5]),
      productType: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  int sse_decode_CastedPrimitive_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_64(deserializer);
    return inner.toInt();
  }

  @protected
  int sse_decode_CastedPrimitive_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_u_64(deserializer);
    return inner.toInt();
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AudioHashesDto sse_decode_audio_hashes_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_standard = sse_decode_opt_String(deserializer);
    var var_high = sse_decode_opt_String(deserializer);
    var var_flac = sse_decode_opt_String(deserializer);
    var var_hiRes = sse_decode_opt_String(deserializer);
    var var_superHash = sse_decode_opt_String(deserializer);
    return AudioHashesDto(
      standard: var_standard,
      high: var_high,
      flac: var_flac,
      hiRes: var_hiRes,
      superHash: var_superHash,
    );
  }

  @protected
  AudioQualityDto sse_decode_audio_quality_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return AudioQualityDto.values[inner];
  }

  @protected
  AuthStateDto sse_decode_auth_state_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_authenticated = sse_decode_bool(deserializer);
    var var_userId = sse_decode_opt_CastedPrimitive_u_64(deserializer);
    var var_vipType = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_fingerprintRegistered = sse_decode_bool(deserializer);
    return AuthStateDto(
      authenticated: var_authenticated,
      userId: var_userId,
      vipType: var_vipType,
      fingerprintRegistered: var_fingerprintRegistered,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bool(deserializer));
  }

  @protected
  PlaylistEditInputDto sse_decode_box_autoadd_playlist_edit_input_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_playlist_edit_input_dto(deserializer));
  }

  @protected
  PlaylistTracksRequestDto sse_decode_box_autoadd_playlist_tracks_request_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_playlist_tracks_request_dto(deserializer));
  }

  @protected
  ResolvePlaybackRequestDto sse_decode_box_autoadd_resolve_playback_request_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_resolve_playback_request_dto(deserializer));
  }

  @protected
  SearchRequestDto sse_decode_box_autoadd_search_request_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_search_request_dto(deserializer));
  }

  @protected
  SongDto sse_decode_box_autoadd_song_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_song_dto(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BridgeError sse_decode_bridge_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_bridge_error_kind(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_code = sse_decode_opt_CastedPrimitive_i_64(deserializer);
    var var_retryable = sse_decode_bool(deserializer);
    return BridgeError(
      kind: var_kind,
      message: var_message,
      code: var_code,
      retryable: var_retryable,
    );
  }

  @protected
  BridgeErrorKind sse_decode_bridge_error_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return BridgeErrorKind.values[inner];
  }

  @protected
  CloudPlaylistDto sse_decode_cloud_playlist_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_listId = sse_decode_opt_CastedPrimitive_u_64(deserializer);
    var var_globalCollectionId = sse_decode_opt_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_intro = sse_decode_opt_String(deserializer);
    var var_artworkUrl = sse_decode_opt_String(deserializer);
    var var_count = sse_decode_opt_CastedPrimitive_u_64(deserializer);
    var var_listType = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_creatorUserId = sse_decode_opt_CastedPrimitive_u_64(deserializer);
    var var_creatorName = sse_decode_opt_String(deserializer);
    var var_isPrivate = sse_decode_bool(deserializer);
    var var_isMyFavorite = sse_decode_bool(deserializer);
    var var_isDefaultCollect = sse_decode_bool(deserializer);
    var var_tags = sse_decode_opt_String(deserializer);
    return CloudPlaylistDto(
      listId: var_listId,
      globalCollectionId: var_globalCollectionId,
      name: var_name,
      intro: var_intro,
      artworkUrl: var_artworkUrl,
      count: var_count,
      listType: var_listType,
      creatorUserId: var_creatorUserId,
      creatorName: var_creatorName,
      isPrivate: var_isPrivate,
      isMyFavorite: var_isMyFavorite,
      isDefaultCollect: var_isDefaultCollect,
      tags: var_tags,
    );
  }

  @protected
  CloudPlaylistPageDto sse_decode_cloud_playlist_page_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_items = sse_decode_list_cloud_playlist_dto(deserializer);
    var var_page = sse_decode_u_32(deserializer);
    var var_pageSize = sse_decode_u_32(deserializer);
    var var_total = sse_decode_opt_CastedPrimitive_u_64(deserializer);
    var var_totalVersion = sse_decode_opt_CastedPrimitive_u_64(deserializer);
    return CloudPlaylistPageDto(
      items: var_items,
      page: var_page,
      pageSize: var_pageSize,
      total: var_total,
      totalVersion: var_totalVersion,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<CloudPlaylistDto> sse_decode_list_cloud_playlist_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CloudPlaylistDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_cloud_playlist_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<PlaylistSearchHitDto> sse_decode_list_playlist_search_hit_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PlaylistSearchHitDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_playlist_search_hit_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SongDto> sse_decode_list_song_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SongDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_song_dto(deserializer));
    }
    return ans_;
  }

  @protected
  int? sse_decode_opt_CastedPrimitive_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_CastedPrimitive_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_CastedPrimitive_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_CastedPrimitive_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bool(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlaybackResolutionDto sse_decode_playback_resolution_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_url = sse_decode_String(deserializer);
        var var_bitRate = sse_decode_opt_CastedPrimitive_u_64(deserializer);
        var var_durationSecs = sse_decode_opt_CastedPrimitive_u_64(
          deserializer,
        );
        return PlaybackResolutionDto_Playable(
          url: var_url,
          bitRate: var_bitRate,
          durationSecs: var_durationSecs,
        );
      case 1:
        var var_url = sse_decode_String(deserializer);
        var var_endMs = sse_decode_opt_CastedPrimitive_u_64(deserializer);
        var var_bitRate = sse_decode_opt_CastedPrimitive_u_64(deserializer);
        var var_durationSecs = sse_decode_opt_CastedPrimitive_u_64(
          deserializer,
        );
        return PlaybackResolutionDto_Preview(
          url: var_url,
          endMs: var_endMs,
          bitRate: var_bitRate,
          durationSecs: var_durationSecs,
        );
      case 2:
        var var_status = sse_decode_opt_CastedPrimitive_i_64(deserializer);
        var var_failProcess = sse_decode_opt_CastedPrimitive_i_64(deserializer);
        return PlaybackResolutionDto_Denied(
          status: var_status,
          failProcess: var_failProcess,
        );
      case 3:
        return PlaybackResolutionDto_Unavailable();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  PlaylistEditInputDto sse_decode_playlist_edit_input_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_listId = sse_decode_CastedPrimitive_u_64(deserializer);
    var var_name = sse_decode_opt_String(deserializer);
    var var_private = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_intro = sse_decode_opt_String(deserializer);
    var var_tags = sse_decode_opt_String(deserializer);
    var var_totalVersion = sse_decode_opt_CastedPrimitive_u_64(deserializer);
    return PlaylistEditInputDto(
      listId: var_listId,
      name: var_name,
      private: var_private,
      intro: var_intro,
      tags: var_tags,
      totalVersion: var_totalVersion,
    );
  }

  @protected
  PlaylistMutationDto sse_decode_playlist_mutation_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_listId = sse_decode_opt_CastedPrimitive_u_64(deserializer);
    var var_globalCollectionId = sse_decode_opt_String(deserializer);
    var var_name = sse_decode_opt_String(deserializer);
    return PlaylistMutationDto(
      listId: var_listId,
      globalCollectionId: var_globalCollectionId,
      name: var_name,
    );
  }

  @protected
  PlaylistSearchHitDto sse_decode_playlist_search_hit_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_specialId = sse_decode_opt_CastedPrimitive_u_64(deserializer);
    var var_globalCollectionId = sse_decode_opt_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_intro = sse_decode_opt_String(deserializer);
    var var_artworkUrl = sse_decode_opt_String(deserializer);
    var var_songCount = sse_decode_opt_CastedPrimitive_u_64(deserializer);
    var var_playCount = sse_decode_opt_CastedPrimitive_u_64(deserializer);
    var var_collectCount = sse_decode_opt_CastedPrimitive_u_64(deserializer);
    var var_creatorName = sse_decode_opt_String(deserializer);
    var var_creatorUserId = sse_decode_opt_CastedPrimitive_u_64(deserializer);
    var var_tags = sse_decode_opt_String(deserializer);
    return PlaylistSearchHitDto(
      specialId: var_specialId,
      globalCollectionId: var_globalCollectionId,
      name: var_name,
      intro: var_intro,
      artworkUrl: var_artworkUrl,
      songCount: var_songCount,
      playCount: var_playCount,
      collectCount: var_collectCount,
      creatorName: var_creatorName,
      creatorUserId: var_creatorUserId,
      tags: var_tags,
    );
  }

  @protected
  PlaylistSearchPageDto sse_decode_playlist_search_page_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_items = sse_decode_list_playlist_search_hit_dto(deserializer);
    var var_page = sse_decode_u_32(deserializer);
    var var_pageSize = sse_decode_u_32(deserializer);
    var var_total = sse_decode_opt_CastedPrimitive_u_64(deserializer);
    return PlaylistSearchPageDto(
      items: var_items,
      page: var_page,
      pageSize: var_pageSize,
      total: var_total,
    );
  }

  @protected
  PlaylistTracksRequestDto sse_decode_playlist_tracks_request_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_listId = sse_decode_opt_CastedPrimitive_u_64(deserializer);
    var var_globalCollectionId = sse_decode_opt_String(deserializer);
    var var_owned = sse_decode_bool(deserializer);
    var var_page = sse_decode_u_32(deserializer);
    var var_pageSize = sse_decode_u_32(deserializer);
    return PlaylistTracksRequestDto(
      listId: var_listId,
      globalCollectionId: var_globalCollectionId,
      owned: var_owned,
      page: var_page,
      pageSize: var_pageSize,
    );
  }

  @protected
  RecommendationDto sse_decode_recommendation_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_subtitle = sse_decode_opt_String(deserializer);
    var var_artworkUrl = sse_decode_opt_String(deserializer);
    var var_creationDate = sse_decode_opt_String(deserializer);
    var var_songs = sse_decode_list_song_dto(deserializer);
    return RecommendationDto(
      title: var_title,
      subtitle: var_subtitle,
      artworkUrl: var_artworkUrl,
      creationDate: var_creationDate,
      songs: var_songs,
    );
  }

  @protected
  ResolvePlaybackRequestDto sse_decode_resolve_playback_request_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_song = sse_decode_song_dto(deserializer);
    var var_quality = sse_decode_audio_quality_dto(deserializer);
    var var_freePreview = sse_decode_bool(deserializer);
    return ResolvePlaybackRequestDto(
      song: var_song,
      quality: var_quality,
      freePreview: var_freePreview,
    );
  }

  @protected
  SdkCapabilitiesDto sse_decode_sdk_capabilities_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_platform = sse_decode_String(deserializer);
    var var_songSearch = sse_decode_bool(deserializer);
    var var_playlistSearch = sse_decode_bool(deserializer);
    var var_dailyRecommendation = sse_decode_bool(deserializer);
    var var_smsAuth = sse_decode_bool(deserializer);
    var var_cloudLibrary = sse_decode_bool(deserializer);
    var var_playlistMutations = sse_decode_bool(deserializer);
    return SdkCapabilitiesDto(
      platform: var_platform,
      songSearch: var_songSearch,
      playlistSearch: var_playlistSearch,
      dailyRecommendation: var_dailyRecommendation,
      smsAuth: var_smsAuth,
      cloudLibrary: var_cloudLibrary,
      playlistMutations: var_playlistMutations,
    );
  }

  @protected
  SearchRequestDto sse_decode_search_request_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_keyword = sse_decode_String(deserializer);
    var var_page = sse_decode_u_32(deserializer);
    var var_pageSize = sse_decode_u_32(deserializer);
    return SearchRequestDto(
      keyword: var_keyword,
      page: var_page,
      pageSize: var_pageSize,
    );
  }

  @protected
  SmsLoginResultDto sse_decode_sms_login_result_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_auth = sse_decode_auth_state_dto(deserializer);
    var var_fingerprintWarning = sse_decode_opt_String(deserializer);
    return SmsLoginResultDto(
      auth: var_auth,
      fingerprintWarning: var_fingerprintWarning,
    );
  }

  @protected
  SongDto sse_decode_song_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_artist = sse_decode_opt_String(deserializer);
    var var_album = sse_decode_opt_String(deserializer);
    var var_durationSecs = sse_decode_opt_CastedPrimitive_u_64(deserializer);
    var var_artworkUrl = sse_decode_opt_String(deserializer);
    var var_privilege = sse_decode_opt_CastedPrimitive_i_64(deserializer);
    var var_albumId = sse_decode_opt_CastedPrimitive_u_64(deserializer);
    var var_mixSongId = sse_decode_opt_CastedPrimitive_u_64(deserializer);
    var var_fileId = sse_decode_opt_CastedPrimitive_u_64(deserializer);
    var var_hashes = sse_decode_audio_hashes_dto(deserializer);
    return SongDto(
      id: var_id,
      title: var_title,
      artist: var_artist,
      album: var_album,
      durationSecs: var_durationSecs,
      artworkUrl: var_artworkUrl,
      privilege: var_privilege,
      albumId: var_albumId,
      mixSongId: var_mixSongId,
      fileId: var_fileId,
      hashes: var_hashes,
    );
  }

  @protected
  SongPageDto sse_decode_song_page_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_items = sse_decode_list_song_dto(deserializer);
    var var_page = sse_decode_u_32(deserializer);
    var var_pageSize = sse_decode_u_32(deserializer);
    var var_total = sse_decode_opt_CastedPrimitive_u_64(deserializer);
    return SongPageDto(
      items: var_items,
      page: var_page,
      pageSize: var_pageSize,
      total: var_total,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  UserProfileDto sse_decode_user_profile_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_userId = sse_decode_opt_CastedPrimitive_u_64(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_username = sse_decode_opt_String(deserializer);
    var var_avatarUrl = sse_decode_opt_String(deserializer);
    var var_gender = sse_decode_opt_CastedPrimitive_i_64(deserializer);
    var var_birthday = sse_decode_opt_String(deserializer);
    var var_city = sse_decode_opt_String(deserializer);
    var var_province = sse_decode_opt_String(deserializer);
    var var_signature = sse_decode_opt_String(deserializer);
    var var_followingCount = sse_decode_opt_CastedPrimitive_u_64(deserializer);
    var var_fanCount = sse_decode_opt_CastedPrimitive_u_64(deserializer);
    var var_visitorCount = sse_decode_opt_CastedPrimitive_u_64(deserializer);
    return UserProfileDto(
      userId: var_userId,
      displayName: var_displayName,
      username: var_username,
      avatarUrl: var_avatarUrl,
      gender: var_gender,
      birthday: var_birthday,
      city: var_city,
      province: var_province,
      signature: var_signature,
      followingCount: var_followingCount,
      fanCount: var_fanCount,
      visitorCount: var_visitorCount,
    );
  }

  @protected
  UserVipDto sse_decode_user_vip_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_vipType = sse_decode_opt_CastedPrimitive_i_64(deserializer);
    var var_musicPackageType = sse_decode_opt_CastedPrimitive_i_64(
      deserializer,
    );
    var var_yearlyType = sse_decode_opt_CastedPrimitive_i_64(deserializer);
    var var_vipEndTime = sse_decode_opt_String(deserializer);
    var var_musicEndTime = sse_decode_opt_String(deserializer);
    var var_yearlyEndTime = sse_decode_opt_String(deserializer);
    var var_productType = sse_decode_opt_String(deserializer);
    return UserVipDto(
      vipType: var_vipType,
      musicPackageType: var_musicPackageType,
      yearlyType: var_yearlyType,
      vipEndTime: var_vipEndTime,
      musicEndTime: var_musicEndTime,
      yearlyEndTime: var_yearlyEndTime,
      productType: var_productType,
    );
  }

  @protected
  void sse_encode_CastedPrimitive_i_64(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(sseEncodeCastedPrimitiveI64(self), serializer);
  }

  @protected
  void sse_encode_CastedPrimitive_u_64(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(sseEncodeCastedPrimitiveU64(self), serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_audio_hashes_dto(
    AudioHashesDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.standard, serializer);
    sse_encode_opt_String(self.high, serializer);
    sse_encode_opt_String(self.flac, serializer);
    sse_encode_opt_String(self.hiRes, serializer);
    sse_encode_opt_String(self.superHash, serializer);
  }

  @protected
  void sse_encode_audio_quality_dto(
    AudioQualityDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_auth_state_dto(AuthStateDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.authenticated, serializer);
    sse_encode_opt_CastedPrimitive_u_64(self.userId, serializer);
    sse_encode_opt_box_autoadd_u_32(self.vipType, serializer);
    sse_encode_bool(self.fingerprintRegistered, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_playlist_edit_input_dto(
    PlaylistEditInputDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_playlist_edit_input_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_playlist_tracks_request_dto(
    PlaylistTracksRequestDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_playlist_tracks_request_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_resolve_playback_request_dto(
    ResolvePlaybackRequestDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_resolve_playback_request_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_search_request_dto(
    SearchRequestDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_search_request_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_song_dto(SongDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_song_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_bridge_error(BridgeError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bridge_error_kind(self.kind, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_opt_CastedPrimitive_i_64(self.code, serializer);
    sse_encode_bool(self.retryable, serializer);
  }

  @protected
  void sse_encode_bridge_error_kind(
    BridgeErrorKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_cloud_playlist_dto(
    CloudPlaylistDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_CastedPrimitive_u_64(self.listId, serializer);
    sse_encode_opt_String(self.globalCollectionId, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.intro, serializer);
    sse_encode_opt_String(self.artworkUrl, serializer);
    sse_encode_opt_CastedPrimitive_u_64(self.count, serializer);
    sse_encode_opt_box_autoadd_u_32(self.listType, serializer);
    sse_encode_opt_CastedPrimitive_u_64(self.creatorUserId, serializer);
    sse_encode_opt_String(self.creatorName, serializer);
    sse_encode_bool(self.isPrivate, serializer);
    sse_encode_bool(self.isMyFavorite, serializer);
    sse_encode_bool(self.isDefaultCollect, serializer);
    sse_encode_opt_String(self.tags, serializer);
  }

  @protected
  void sse_encode_cloud_playlist_page_dto(
    CloudPlaylistPageDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_cloud_playlist_dto(self.items, serializer);
    sse_encode_u_32(self.page, serializer);
    sse_encode_u_32(self.pageSize, serializer);
    sse_encode_opt_CastedPrimitive_u_64(self.total, serializer);
    sse_encode_opt_CastedPrimitive_u_64(self.totalVersion, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_cloud_playlist_dto(
    List<CloudPlaylistDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_cloud_playlist_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_playlist_search_hit_dto(
    List<PlaylistSearchHitDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_playlist_search_hit_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_song_dto(List<SongDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_song_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_CastedPrimitive_i_64(
    int? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_CastedPrimitive_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_CastedPrimitive_u_64(
    int? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_CastedPrimitive_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bool(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_playback_resolution_dto(
    PlaybackResolutionDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case PlaybackResolutionDto_Playable(
        url: final url,
        bitRate: final bitRate,
        durationSecs: final durationSecs,
      ):
        sse_encode_i_32(0, serializer);
        sse_encode_String(url, serializer);
        sse_encode_opt_CastedPrimitive_u_64(bitRate, serializer);
        sse_encode_opt_CastedPrimitive_u_64(durationSecs, serializer);
      case PlaybackResolutionDto_Preview(
        url: final url,
        endMs: final endMs,
        bitRate: final bitRate,
        durationSecs: final durationSecs,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_String(url, serializer);
        sse_encode_opt_CastedPrimitive_u_64(endMs, serializer);
        sse_encode_opt_CastedPrimitive_u_64(bitRate, serializer);
        sse_encode_opt_CastedPrimitive_u_64(durationSecs, serializer);
      case PlaybackResolutionDto_Denied(
        status: final status,
        failProcess: final failProcess,
      ):
        sse_encode_i_32(2, serializer);
        sse_encode_opt_CastedPrimitive_i_64(status, serializer);
        sse_encode_opt_CastedPrimitive_i_64(failProcess, serializer);
      case PlaybackResolutionDto_Unavailable():
        sse_encode_i_32(3, serializer);
    }
  }

  @protected
  void sse_encode_playlist_edit_input_dto(
    PlaylistEditInputDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_CastedPrimitive_u_64(self.listId, serializer);
    sse_encode_opt_String(self.name, serializer);
    sse_encode_opt_box_autoadd_bool(self.private, serializer);
    sse_encode_opt_String(self.intro, serializer);
    sse_encode_opt_String(self.tags, serializer);
    sse_encode_opt_CastedPrimitive_u_64(self.totalVersion, serializer);
  }

  @protected
  void sse_encode_playlist_mutation_dto(
    PlaylistMutationDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_CastedPrimitive_u_64(self.listId, serializer);
    sse_encode_opt_String(self.globalCollectionId, serializer);
    sse_encode_opt_String(self.name, serializer);
  }

  @protected
  void sse_encode_playlist_search_hit_dto(
    PlaylistSearchHitDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_CastedPrimitive_u_64(self.specialId, serializer);
    sse_encode_opt_String(self.globalCollectionId, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.intro, serializer);
    sse_encode_opt_String(self.artworkUrl, serializer);
    sse_encode_opt_CastedPrimitive_u_64(self.songCount, serializer);
    sse_encode_opt_CastedPrimitive_u_64(self.playCount, serializer);
    sse_encode_opt_CastedPrimitive_u_64(self.collectCount, serializer);
    sse_encode_opt_String(self.creatorName, serializer);
    sse_encode_opt_CastedPrimitive_u_64(self.creatorUserId, serializer);
    sse_encode_opt_String(self.tags, serializer);
  }

  @protected
  void sse_encode_playlist_search_page_dto(
    PlaylistSearchPageDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_playlist_search_hit_dto(self.items, serializer);
    sse_encode_u_32(self.page, serializer);
    sse_encode_u_32(self.pageSize, serializer);
    sse_encode_opt_CastedPrimitive_u_64(self.total, serializer);
  }

  @protected
  void sse_encode_playlist_tracks_request_dto(
    PlaylistTracksRequestDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_CastedPrimitive_u_64(self.listId, serializer);
    sse_encode_opt_String(self.globalCollectionId, serializer);
    sse_encode_bool(self.owned, serializer);
    sse_encode_u_32(self.page, serializer);
    sse_encode_u_32(self.pageSize, serializer);
  }

  @protected
  void sse_encode_recommendation_dto(
    RecommendationDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.subtitle, serializer);
    sse_encode_opt_String(self.artworkUrl, serializer);
    sse_encode_opt_String(self.creationDate, serializer);
    sse_encode_list_song_dto(self.songs, serializer);
  }

  @protected
  void sse_encode_resolve_playback_request_dto(
    ResolvePlaybackRequestDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_song_dto(self.song, serializer);
    sse_encode_audio_quality_dto(self.quality, serializer);
    sse_encode_bool(self.freePreview, serializer);
  }

  @protected
  void sse_encode_sdk_capabilities_dto(
    SdkCapabilitiesDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.platform, serializer);
    sse_encode_bool(self.songSearch, serializer);
    sse_encode_bool(self.playlistSearch, serializer);
    sse_encode_bool(self.dailyRecommendation, serializer);
    sse_encode_bool(self.smsAuth, serializer);
    sse_encode_bool(self.cloudLibrary, serializer);
    sse_encode_bool(self.playlistMutations, serializer);
  }

  @protected
  void sse_encode_search_request_dto(
    SearchRequestDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.keyword, serializer);
    sse_encode_u_32(self.page, serializer);
    sse_encode_u_32(self.pageSize, serializer);
  }

  @protected
  void sse_encode_sms_login_result_dto(
    SmsLoginResultDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_auth_state_dto(self.auth, serializer);
    sse_encode_opt_String(self.fingerprintWarning, serializer);
  }

  @protected
  void sse_encode_song_dto(SongDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.artist, serializer);
    sse_encode_opt_String(self.album, serializer);
    sse_encode_opt_CastedPrimitive_u_64(self.durationSecs, serializer);
    sse_encode_opt_String(self.artworkUrl, serializer);
    sse_encode_opt_CastedPrimitive_i_64(self.privilege, serializer);
    sse_encode_opt_CastedPrimitive_u_64(self.albumId, serializer);
    sse_encode_opt_CastedPrimitive_u_64(self.mixSongId, serializer);
    sse_encode_opt_CastedPrimitive_u_64(self.fileId, serializer);
    sse_encode_audio_hashes_dto(self.hashes, serializer);
  }

  @protected
  void sse_encode_song_page_dto(SongPageDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_song_dto(self.items, serializer);
    sse_encode_u_32(self.page, serializer);
    sse_encode_u_32(self.pageSize, serializer);
    sse_encode_opt_CastedPrimitive_u_64(self.total, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_user_profile_dto(
    UserProfileDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_CastedPrimitive_u_64(self.userId, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_opt_String(self.username, serializer);
    sse_encode_opt_String(self.avatarUrl, serializer);
    sse_encode_opt_CastedPrimitive_i_64(self.gender, serializer);
    sse_encode_opt_String(self.birthday, serializer);
    sse_encode_opt_String(self.city, serializer);
    sse_encode_opt_String(self.province, serializer);
    sse_encode_opt_String(self.signature, serializer);
    sse_encode_opt_CastedPrimitive_u_64(self.followingCount, serializer);
    sse_encode_opt_CastedPrimitive_u_64(self.fanCount, serializer);
    sse_encode_opt_CastedPrimitive_u_64(self.visitorCount, serializer);
  }

  @protected
  void sse_encode_user_vip_dto(UserVipDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_CastedPrimitive_i_64(self.vipType, serializer);
    sse_encode_opt_CastedPrimitive_i_64(self.musicPackageType, serializer);
    sse_encode_opt_CastedPrimitive_i_64(self.yearlyType, serializer);
    sse_encode_opt_String(self.vipEndTime, serializer);
    sse_encode_opt_String(self.musicEndTime, serializer);
    sse_encode_opt_String(self.yearlyEndTime, serializer);
    sse_encode_opt_String(self.productType, serializer);
  }
}
