// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/sdk.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  int dco_decode_CastedPrimitive_i_64(dynamic raw);

  @protected
  int dco_decode_CastedPrimitive_u_64(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AudioHashesDto dco_decode_audio_hashes_dto(dynamic raw);

  @protected
  AudioQualityDto dco_decode_audio_quality_dto(dynamic raw);

  @protected
  AuthStateDto dco_decode_auth_state_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  PlaylistEditInputDto dco_decode_box_autoadd_playlist_edit_input_dto(
    dynamic raw,
  );

  @protected
  PlaylistTracksRequestDto dco_decode_box_autoadd_playlist_tracks_request_dto(
    dynamic raw,
  );

  @protected
  ResolvePlaybackRequestDto dco_decode_box_autoadd_resolve_playback_request_dto(
    dynamic raw,
  );

  @protected
  SearchRequestDto dco_decode_box_autoadd_search_request_dto(dynamic raw);

  @protected
  SongDto dco_decode_box_autoadd_song_dto(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BridgeError dco_decode_bridge_error(dynamic raw);

  @protected
  BridgeErrorKind dco_decode_bridge_error_kind(dynamic raw);

  @protected
  CloudPlaylistDto dco_decode_cloud_playlist_dto(dynamic raw);

  @protected
  CloudPlaylistPageDto dco_decode_cloud_playlist_page_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<CloudPlaylistDto> dco_decode_list_cloud_playlist_dto(dynamic raw);

  @protected
  List<PlaylistSearchHitDto> dco_decode_list_playlist_search_hit_dto(
    dynamic raw,
  );

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SongDto> dco_decode_list_song_dto(dynamic raw);

  @protected
  int? dco_decode_opt_CastedPrimitive_i_64(dynamic raw);

  @protected
  int? dco_decode_opt_CastedPrimitive_u_64(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  PlaybackResolutionDto dco_decode_playback_resolution_dto(dynamic raw);

  @protected
  PlaylistEditInputDto dco_decode_playlist_edit_input_dto(dynamic raw);

  @protected
  PlaylistMutationDto dco_decode_playlist_mutation_dto(dynamic raw);

  @protected
  PlaylistSearchHitDto dco_decode_playlist_search_hit_dto(dynamic raw);

  @protected
  PlaylistSearchPageDto dco_decode_playlist_search_page_dto(dynamic raw);

  @protected
  PlaylistTracksRequestDto dco_decode_playlist_tracks_request_dto(dynamic raw);

  @protected
  RecommendationDto dco_decode_recommendation_dto(dynamic raw);

  @protected
  ResolvePlaybackRequestDto dco_decode_resolve_playback_request_dto(
    dynamic raw,
  );

  @protected
  SdkCapabilitiesDto dco_decode_sdk_capabilities_dto(dynamic raw);

  @protected
  SearchRequestDto dco_decode_search_request_dto(dynamic raw);

  @protected
  SmsLoginResultDto dco_decode_sms_login_result_dto(dynamic raw);

  @protected
  SongDto dco_decode_song_dto(dynamic raw);

  @protected
  SongPageDto dco_decode_song_page_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UserProfileDto dco_decode_user_profile_dto(dynamic raw);

  @protected
  UserVipDto dco_decode_user_vip_dto(dynamic raw);

  @protected
  int sse_decode_CastedPrimitive_i_64(SseDeserializer deserializer);

  @protected
  int sse_decode_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AudioHashesDto sse_decode_audio_hashes_dto(SseDeserializer deserializer);

  @protected
  AudioQualityDto sse_decode_audio_quality_dto(SseDeserializer deserializer);

  @protected
  AuthStateDto sse_decode_auth_state_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  PlaylistEditInputDto sse_decode_box_autoadd_playlist_edit_input_dto(
    SseDeserializer deserializer,
  );

  @protected
  PlaylistTracksRequestDto sse_decode_box_autoadd_playlist_tracks_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  ResolvePlaybackRequestDto sse_decode_box_autoadd_resolve_playback_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  SearchRequestDto sse_decode_box_autoadd_search_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  SongDto sse_decode_box_autoadd_song_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BridgeError sse_decode_bridge_error(SseDeserializer deserializer);

  @protected
  BridgeErrorKind sse_decode_bridge_error_kind(SseDeserializer deserializer);

  @protected
  CloudPlaylistDto sse_decode_cloud_playlist_dto(SseDeserializer deserializer);

  @protected
  CloudPlaylistPageDto sse_decode_cloud_playlist_page_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<CloudPlaylistDto> sse_decode_list_cloud_playlist_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<PlaylistSearchHitDto> sse_decode_list_playlist_search_hit_dto(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SongDto> sse_decode_list_song_dto(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_CastedPrimitive_i_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  PlaybackResolutionDto sse_decode_playback_resolution_dto(
    SseDeserializer deserializer,
  );

  @protected
  PlaylistEditInputDto sse_decode_playlist_edit_input_dto(
    SseDeserializer deserializer,
  );

  @protected
  PlaylistMutationDto sse_decode_playlist_mutation_dto(
    SseDeserializer deserializer,
  );

  @protected
  PlaylistSearchHitDto sse_decode_playlist_search_hit_dto(
    SseDeserializer deserializer,
  );

  @protected
  PlaylistSearchPageDto sse_decode_playlist_search_page_dto(
    SseDeserializer deserializer,
  );

  @protected
  PlaylistTracksRequestDto sse_decode_playlist_tracks_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  RecommendationDto sse_decode_recommendation_dto(SseDeserializer deserializer);

  @protected
  ResolvePlaybackRequestDto sse_decode_resolve_playback_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  SdkCapabilitiesDto sse_decode_sdk_capabilities_dto(
    SseDeserializer deserializer,
  );

  @protected
  SearchRequestDto sse_decode_search_request_dto(SseDeserializer deserializer);

  @protected
  SmsLoginResultDto sse_decode_sms_login_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  SongDto sse_decode_song_dto(SseDeserializer deserializer);

  @protected
  SongPageDto sse_decode_song_page_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UserProfileDto sse_decode_user_profile_dto(SseDeserializer deserializer);

  @protected
  UserVipDto sse_decode_user_vip_dto(SseDeserializer deserializer);

  @protected
  void sse_encode_CastedPrimitive_i_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_CastedPrimitive_u_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_audio_hashes_dto(
    AudioHashesDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_audio_quality_dto(
    AudioQualityDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_auth_state_dto(AuthStateDto self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_playlist_edit_input_dto(
    PlaylistEditInputDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_playlist_tracks_request_dto(
    PlaylistTracksRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_resolve_playback_request_dto(
    ResolvePlaybackRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_search_request_dto(
    SearchRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_song_dto(SongDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_error(BridgeError self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_error_kind(
    BridgeErrorKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cloud_playlist_dto(
    CloudPlaylistDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cloud_playlist_page_dto(
    CloudPlaylistPageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_cloud_playlist_dto(
    List<CloudPlaylistDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_playlist_search_hit_dto(
    List<PlaylistSearchHitDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_song_dto(List<SongDto> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_CastedPrimitive_i_64(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_CastedPrimitive_u_64(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_playback_resolution_dto(
    PlaybackResolutionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_playlist_edit_input_dto(
    PlaylistEditInputDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_playlist_mutation_dto(
    PlaylistMutationDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_playlist_search_hit_dto(
    PlaylistSearchHitDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_playlist_search_page_dto(
    PlaylistSearchPageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_playlist_tracks_request_dto(
    PlaylistTracksRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_recommendation_dto(
    RecommendationDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_resolve_playback_request_dto(
    ResolvePlaybackRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sdk_capabilities_dto(
    SdkCapabilitiesDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_search_request_dto(
    SearchRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sms_login_result_dto(
    SmsLoginResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_song_dto(SongDto self, SseSerializer serializer);

  @protected
  void sse_encode_song_page_dto(SongPageDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_user_profile_dto(
    UserProfileDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_user_vip_dto(UserVipDto self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
