// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/sdk.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  int dco_decode_CastedPrimitive_i_64(dynamic raw);

  @protected
  int dco_decode_CastedPrimitive_u_64(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AudioHashesDto dco_decode_audio_hashes_dto(dynamic raw);

  @protected
  AudioQualityDto dco_decode_audio_quality_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ResolvePlaybackRequestDto dco_decode_box_autoadd_resolve_playback_request_dto(
    dynamic raw,
  );

  @protected
  SearchSongsRequestDto dco_decode_box_autoadd_search_songs_request_dto(
    dynamic raw,
  );

  @protected
  BridgeError dco_decode_bridge_error(dynamic raw);

  @protected
  BridgeErrorKind dco_decode_bridge_error_kind(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SongDto> dco_decode_list_song_dto(dynamic raw);

  @protected
  int? dco_decode_opt_CastedPrimitive_i_64(dynamic raw);

  @protected
  int? dco_decode_opt_CastedPrimitive_u_64(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlaybackResolutionDto dco_decode_playback_resolution_dto(dynamic raw);

  @protected
  RecommendationDto dco_decode_recommendation_dto(dynamic raw);

  @protected
  ResolvePlaybackRequestDto dco_decode_resolve_playback_request_dto(
    dynamic raw,
  );

  @protected
  SdkCapabilitiesDto dco_decode_sdk_capabilities_dto(dynamic raw);

  @protected
  SearchPageDto dco_decode_search_page_dto(dynamic raw);

  @protected
  SearchSongsRequestDto dco_decode_search_songs_request_dto(dynamic raw);

  @protected
  SongDto dco_decode_song_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  int sse_decode_CastedPrimitive_i_64(SseDeserializer deserializer);

  @protected
  int sse_decode_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AudioHashesDto sse_decode_audio_hashes_dto(SseDeserializer deserializer);

  @protected
  AudioQualityDto sse_decode_audio_quality_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ResolvePlaybackRequestDto sse_decode_box_autoadd_resolve_playback_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  SearchSongsRequestDto sse_decode_box_autoadd_search_songs_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeError sse_decode_bridge_error(SseDeserializer deserializer);

  @protected
  BridgeErrorKind sse_decode_bridge_error_kind(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SongDto> sse_decode_list_song_dto(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_CastedPrimitive_i_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlaybackResolutionDto sse_decode_playback_resolution_dto(
    SseDeserializer deserializer,
  );

  @protected
  RecommendationDto sse_decode_recommendation_dto(SseDeserializer deserializer);

  @protected
  ResolvePlaybackRequestDto sse_decode_resolve_playback_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  SdkCapabilitiesDto sse_decode_sdk_capabilities_dto(
    SseDeserializer deserializer,
  );

  @protected
  SearchPageDto sse_decode_search_page_dto(SseDeserializer deserializer);

  @protected
  SearchSongsRequestDto sse_decode_search_songs_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  SongDto sse_decode_song_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_CastedPrimitive_i_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_CastedPrimitive_u_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_audio_hashes_dto(
    AudioHashesDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_audio_quality_dto(
    AudioQualityDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_resolve_playback_request_dto(
    ResolvePlaybackRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_search_songs_request_dto(
    SearchSongsRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_error(BridgeError self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_error_kind(
    BridgeErrorKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_song_dto(List<SongDto> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_CastedPrimitive_i_64(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_CastedPrimitive_u_64(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_playback_resolution_dto(
    PlaybackResolutionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_recommendation_dto(
    RecommendationDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_resolve_playback_request_dto(
    ResolvePlaybackRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sdk_capabilities_dto(
    SdkCapabilitiesDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_search_page_dto(SearchPageDto self, SseSerializer serializer);

  @protected
  void sse_encode_search_songs_request_dto(
    SearchSongsRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_song_dto(SongDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
