// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/sdk.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSdkInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1332007897;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'kugou_bridge',
        ioDirectory: 'native/kugou_bridge/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiSdkExportSession();

  Future<RecommendationDto> crateApiSdkGetEverydayRecommendations();

  SdkCapabilitiesDto crateApiSdkGetSdkCapabilities();

  Future<void> crateApiSdkImportSession({required String value});

  Future<void> crateApiSdkInitApp();

  Future<SdkCapabilitiesDto> crateApiSdkInitializeSdk();

  Future<PlaybackResolutionDto> crateApiSdkResolvePlayback({
    required ResolvePlaybackRequestDto request,
  });

  Future<SearchPageDto> crateApiSdkSearchSongs({
    required SearchSongsRequestDto request,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiSdkExportSession() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSdkExportSessionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSdkExportSessionConstMeta =>
      const TaskConstMeta(debugName: "export_session", argNames: []);

  @override
  Future<RecommendationDto> crateApiSdkGetEverydayRecommendations() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_recommendation_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSdkGetEverydayRecommendationsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSdkGetEverydayRecommendationsConstMeta =>
      const TaskConstMeta(
        debugName: "get_everyday_recommendations",
        argNames: [],
      );

  @override
  SdkCapabilitiesDto crateApiSdkGetSdkCapabilities() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sdk_capabilities_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSdkGetSdkCapabilitiesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSdkGetSdkCapabilitiesConstMeta =>
      const TaskConstMeta(debugName: "get_sdk_capabilities", argNames: []);

  @override
  Future<void> crateApiSdkImportSession({required String value}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(value, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSdkImportSessionConstMeta,
        argValues: [value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSdkImportSessionConstMeta =>
      const TaskConstMeta(debugName: "import_session", argNames: ["value"]);

  @override
  Future<void> crateApiSdkInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSdkInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSdkInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<SdkCapabilitiesDto> crateApiSdkInitializeSdk() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sdk_capabilities_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSdkInitializeSdkConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSdkInitializeSdkConstMeta =>
      const TaskConstMeta(debugName: "initialize_sdk", argNames: []);

  @override
  Future<PlaybackResolutionDto> crateApiSdkResolvePlayback({
    required ResolvePlaybackRequestDto request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_resolve_playback_request_dto(
            request,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_playback_resolution_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSdkResolvePlaybackConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSdkResolvePlaybackConstMeta =>
      const TaskConstMeta(debugName: "resolve_playback", argNames: ["request"]);

  @override
  Future<SearchPageDto> crateApiSdkSearchSongs({
    required SearchSongsRequestDto request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_search_songs_request_dto(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_search_page_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSdkSearchSongsConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSdkSearchSongsConstMeta =>
      const TaskConstMeta(debugName: "search_songs", argNames: ["request"]);

  @protected
  int dco_decode_CastedPrimitive_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError(
      'Not implemented in this codec, please use the other one',
    );
  }

  @protected
  int dco_decode_CastedPrimitive_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError(
      'Not implemented in this codec, please use the other one',
    );
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AudioHashesDto dco_decode_audio_hashes_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return AudioHashesDto(
      standard: dco_decode_opt_String(arr[0]),
      high: dco_decode_opt_String(arr[1]),
      flac: dco_decode_opt_String(arr[2]),
      hiRes: dco_decode_opt_String(arr[3]),
      superHash: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  AudioQualityDto dco_decode_audio_quality_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AudioQualityDto.values[raw as int];
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ResolvePlaybackRequestDto dco_decode_box_autoadd_resolve_playback_request_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_resolve_playback_request_dto(raw);
  }

  @protected
  SearchSongsRequestDto dco_decode_box_autoadd_search_songs_request_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_search_songs_request_dto(raw);
  }

  @protected
  BridgeError dco_decode_bridge_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return BridgeError(
      kind: dco_decode_bridge_error_kind(arr[0]),
      message: dco_decode_String(arr[1]),
      code: dco_decode_opt_CastedPrimitive_i_64(arr[2]),
      retryable: dco_decode_bool(arr[3]),
    );
  }

  @protected
  BridgeErrorKind dco_decode_bridge_error_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BridgeErrorKind.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SongDto> dco_decode_list_song_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_song_dto).toList();
  }

  @protected
  int? dco_decode_opt_CastedPrimitive_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_CastedPrimitive_i_64(raw);
  }

  @protected
  int? dco_decode_opt_CastedPrimitive_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_CastedPrimitive_u_64(raw);
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlaybackResolutionDto dco_decode_playback_resolution_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return PlaybackResolutionDto_Playable(
          url: dco_decode_String(raw[1]),
          bitRate: dco_decode_opt_CastedPrimitive_u_64(raw[2]),
          durationSecs: dco_decode_opt_CastedPrimitive_u_64(raw[3]),
        );
      case 1:
        return PlaybackResolutionDto_Preview(
          url: dco_decode_String(raw[1]),
          endMs: dco_decode_opt_CastedPrimitive_u_64(raw[2]),
          bitRate: dco_decode_opt_CastedPrimitive_u_64(raw[3]),
          durationSecs: dco_decode_opt_CastedPrimitive_u_64(raw[4]),
        );
      case 2:
        return PlaybackResolutionDto_Denied(
          status: dco_decode_opt_CastedPrimitive_i_64(raw[1]),
          failProcess: dco_decode_opt_CastedPrimitive_i_64(raw[2]),
        );
      case 3:
        return PlaybackResolutionDto_Unavailable();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  RecommendationDto dco_decode_recommendation_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return RecommendationDto(
      title: dco_decode_String(arr[0]),
      subtitle: dco_decode_opt_String(arr[1]),
      artworkUrl: dco_decode_opt_String(arr[2]),
      creationDate: dco_decode_opt_String(arr[3]),
      songs: dco_decode_list_song_dto(arr[4]),
    );
  }

  @protected
  ResolvePlaybackRequestDto dco_decode_resolve_playback_request_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ResolvePlaybackRequestDto(
      song: dco_decode_song_dto(arr[0]),
      quality: dco_decode_audio_quality_dto(arr[1]),
      freePreview: dco_decode_bool(arr[2]),
    );
  }

  @protected
  SdkCapabilitiesDto dco_decode_sdk_capabilities_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return SdkCapabilitiesDto(
      platform: dco_decode_String(arr[0]),
      songSearch: dco_decode_bool(arr[1]),
      dailyRecommendation: dco_decode_bool(arr[2]),
      rank: dco_decode_bool(arr[3]),
      trendingPlaylists: dco_decode_bool(arr[4]),
      lyrics: dco_decode_bool(arr[5]),
      qrAuth: dco_decode_bool(arr[6]),
      cloudLibrary: dco_decode_bool(arr[7]),
    );
  }

  @protected
  SearchPageDto dco_decode_search_page_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SearchPageDto(
      items: dco_decode_list_song_dto(arr[0]),
      page: dco_decode_u_32(arr[1]),
      pageSize: dco_decode_u_32(arr[2]),
      total: dco_decode_opt_CastedPrimitive_u_64(arr[3]),
    );
  }

  @protected
  SearchSongsRequestDto dco_decode_search_songs_request_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SearchSongsRequestDto(
      keyword: dco_decode_String(arr[0]),
      page: dco_decode_u_32(arr[1]),
      pageSize: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  SongDto dco_decode_song_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return SongDto(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      artist: dco_decode_opt_String(arr[2]),
      album: dco_decode_opt_String(arr[3]),
      durationSecs: dco_decode_opt_CastedPrimitive_u_64(arr[4]),
      artworkUrl: dco_decode_opt_String(arr[5]),
      privilege: dco_decode_opt_CastedPrimitive_i_64(arr[6]),
      albumId: dco_decode_opt_CastedPrimitive_u_64(arr[7]),
      mixSongId: dco_decode_opt_CastedPrimitive_u_64(arr[8]),
      hashes: dco_decode_audio_hashes_dto(arr[9]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  int sse_decode_CastedPrimitive_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_64(deserializer);
    return inner.toInt();
  }

  @protected
  int sse_decode_CastedPrimitive_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_u_64(deserializer);
    return inner.toInt();
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AudioHashesDto sse_decode_audio_hashes_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_standard = sse_decode_opt_String(deserializer);
    var var_high = sse_decode_opt_String(deserializer);
    var var_flac = sse_decode_opt_String(deserializer);
    var var_hiRes = sse_decode_opt_String(deserializer);
    var var_superHash = sse_decode_opt_String(deserializer);
    return AudioHashesDto(
      standard: var_standard,
      high: var_high,
      flac: var_flac,
      hiRes: var_hiRes,
      superHash: var_superHash,
    );
  }

  @protected
  AudioQualityDto sse_decode_audio_quality_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return AudioQualityDto.values[inner];
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ResolvePlaybackRequestDto sse_decode_box_autoadd_resolve_playback_request_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_resolve_playback_request_dto(deserializer));
  }

  @protected
  SearchSongsRequestDto sse_decode_box_autoadd_search_songs_request_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_search_songs_request_dto(deserializer));
  }

  @protected
  BridgeError sse_decode_bridge_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_bridge_error_kind(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_code = sse_decode_opt_CastedPrimitive_i_64(deserializer);
    var var_retryable = sse_decode_bool(deserializer);
    return BridgeError(
      kind: var_kind,
      message: var_message,
      code: var_code,
      retryable: var_retryable,
    );
  }

  @protected
  BridgeErrorKind sse_decode_bridge_error_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return BridgeErrorKind.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SongDto> sse_decode_list_song_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SongDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_song_dto(deserializer));
    }
    return ans_;
  }

  @protected
  int? sse_decode_opt_CastedPrimitive_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_CastedPrimitive_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_CastedPrimitive_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_CastedPrimitive_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlaybackResolutionDto sse_decode_playback_resolution_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_url = sse_decode_String(deserializer);
        var var_bitRate = sse_decode_opt_CastedPrimitive_u_64(deserializer);
        var var_durationSecs = sse_decode_opt_CastedPrimitive_u_64(
          deserializer,
        );
        return PlaybackResolutionDto_Playable(
          url: var_url,
          bitRate: var_bitRate,
          durationSecs: var_durationSecs,
        );
      case 1:
        var var_url = sse_decode_String(deserializer);
        var var_endMs = sse_decode_opt_CastedPrimitive_u_64(deserializer);
        var var_bitRate = sse_decode_opt_CastedPrimitive_u_64(deserializer);
        var var_durationSecs = sse_decode_opt_CastedPrimitive_u_64(
          deserializer,
        );
        return PlaybackResolutionDto_Preview(
          url: var_url,
          endMs: var_endMs,
          bitRate: var_bitRate,
          durationSecs: var_durationSecs,
        );
      case 2:
        var var_status = sse_decode_opt_CastedPrimitive_i_64(deserializer);
        var var_failProcess = sse_decode_opt_CastedPrimitive_i_64(deserializer);
        return PlaybackResolutionDto_Denied(
          status: var_status,
          failProcess: var_failProcess,
        );
      case 3:
        return PlaybackResolutionDto_Unavailable();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  RecommendationDto sse_decode_recommendation_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_subtitle = sse_decode_opt_String(deserializer);
    var var_artworkUrl = sse_decode_opt_String(deserializer);
    var var_creationDate = sse_decode_opt_String(deserializer);
    var var_songs = sse_decode_list_song_dto(deserializer);
    return RecommendationDto(
      title: var_title,
      subtitle: var_subtitle,
      artworkUrl: var_artworkUrl,
      creationDate: var_creationDate,
      songs: var_songs,
    );
  }

  @protected
  ResolvePlaybackRequestDto sse_decode_resolve_playback_request_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_song = sse_decode_song_dto(deserializer);
    var var_quality = sse_decode_audio_quality_dto(deserializer);
    var var_freePreview = sse_decode_bool(deserializer);
    return ResolvePlaybackRequestDto(
      song: var_song,
      quality: var_quality,
      freePreview: var_freePreview,
    );
  }

  @protected
  SdkCapabilitiesDto sse_decode_sdk_capabilities_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_platform = sse_decode_String(deserializer);
    var var_songSearch = sse_decode_bool(deserializer);
    var var_dailyRecommendation = sse_decode_bool(deserializer);
    var var_rank = sse_decode_bool(deserializer);
    var var_trendingPlaylists = sse_decode_bool(deserializer);
    var var_lyrics = sse_decode_bool(deserializer);
    var var_qrAuth = sse_decode_bool(deserializer);
    var var_cloudLibrary = sse_decode_bool(deserializer);
    return SdkCapabilitiesDto(
      platform: var_platform,
      songSearch: var_songSearch,
      dailyRecommendation: var_dailyRecommendation,
      rank: var_rank,
      trendingPlaylists: var_trendingPlaylists,
      lyrics: var_lyrics,
      qrAuth: var_qrAuth,
      cloudLibrary: var_cloudLibrary,
    );
  }

  @protected
  SearchPageDto sse_decode_search_page_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_items = sse_decode_list_song_dto(deserializer);
    var var_page = sse_decode_u_32(deserializer);
    var var_pageSize = sse_decode_u_32(deserializer);
    var var_total = sse_decode_opt_CastedPrimitive_u_64(deserializer);
    return SearchPageDto(
      items: var_items,
      page: var_page,
      pageSize: var_pageSize,
      total: var_total,
    );
  }

  @protected
  SearchSongsRequestDto sse_decode_search_songs_request_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_keyword = sse_decode_String(deserializer);
    var var_page = sse_decode_u_32(deserializer);
    var var_pageSize = sse_decode_u_32(deserializer);
    return SearchSongsRequestDto(
      keyword: var_keyword,
      page: var_page,
      pageSize: var_pageSize,
    );
  }

  @protected
  SongDto sse_decode_song_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_artist = sse_decode_opt_String(deserializer);
    var var_album = sse_decode_opt_String(deserializer);
    var var_durationSecs = sse_decode_opt_CastedPrimitive_u_64(deserializer);
    var var_artworkUrl = sse_decode_opt_String(deserializer);
    var var_privilege = sse_decode_opt_CastedPrimitive_i_64(deserializer);
    var var_albumId = sse_decode_opt_CastedPrimitive_u_64(deserializer);
    var var_mixSongId = sse_decode_opt_CastedPrimitive_u_64(deserializer);
    var var_hashes = sse_decode_audio_hashes_dto(deserializer);
    return SongDto(
      id: var_id,
      title: var_title,
      artist: var_artist,
      album: var_album,
      durationSecs: var_durationSecs,
      artworkUrl: var_artworkUrl,
      privilege: var_privilege,
      albumId: var_albumId,
      mixSongId: var_mixSongId,
      hashes: var_hashes,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_CastedPrimitive_i_64(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(sseEncodeCastedPrimitiveI64(self), serializer);
  }

  @protected
  void sse_encode_CastedPrimitive_u_64(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(sseEncodeCastedPrimitiveU64(self), serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_audio_hashes_dto(
    AudioHashesDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.standard, serializer);
    sse_encode_opt_String(self.high, serializer);
    sse_encode_opt_String(self.flac, serializer);
    sse_encode_opt_String(self.hiRes, serializer);
    sse_encode_opt_String(self.superHash, serializer);
  }

  @protected
  void sse_encode_audio_quality_dto(
    AudioQualityDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_resolve_playback_request_dto(
    ResolvePlaybackRequestDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_resolve_playback_request_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_search_songs_request_dto(
    SearchSongsRequestDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_search_songs_request_dto(self, serializer);
  }

  @protected
  void sse_encode_bridge_error(BridgeError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bridge_error_kind(self.kind, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_opt_CastedPrimitive_i_64(self.code, serializer);
    sse_encode_bool(self.retryable, serializer);
  }

  @protected
  void sse_encode_bridge_error_kind(
    BridgeErrorKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_song_dto(List<SongDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_song_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_CastedPrimitive_i_64(
    int? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_CastedPrimitive_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_CastedPrimitive_u_64(
    int? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_CastedPrimitive_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_playback_resolution_dto(
    PlaybackResolutionDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case PlaybackResolutionDto_Playable(
        url: final url,
        bitRate: final bitRate,
        durationSecs: final durationSecs,
      ):
        sse_encode_i_32(0, serializer);
        sse_encode_String(url, serializer);
        sse_encode_opt_CastedPrimitive_u_64(bitRate, serializer);
        sse_encode_opt_CastedPrimitive_u_64(durationSecs, serializer);
      case PlaybackResolutionDto_Preview(
        url: final url,
        endMs: final endMs,
        bitRate: final bitRate,
        durationSecs: final durationSecs,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_String(url, serializer);
        sse_encode_opt_CastedPrimitive_u_64(endMs, serializer);
        sse_encode_opt_CastedPrimitive_u_64(bitRate, serializer);
        sse_encode_opt_CastedPrimitive_u_64(durationSecs, serializer);
      case PlaybackResolutionDto_Denied(
        status: final status,
        failProcess: final failProcess,
      ):
        sse_encode_i_32(2, serializer);
        sse_encode_opt_CastedPrimitive_i_64(status, serializer);
        sse_encode_opt_CastedPrimitive_i_64(failProcess, serializer);
      case PlaybackResolutionDto_Unavailable():
        sse_encode_i_32(3, serializer);
    }
  }

  @protected
  void sse_encode_recommendation_dto(
    RecommendationDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.subtitle, serializer);
    sse_encode_opt_String(self.artworkUrl, serializer);
    sse_encode_opt_String(self.creationDate, serializer);
    sse_encode_list_song_dto(self.songs, serializer);
  }

  @protected
  void sse_encode_resolve_playback_request_dto(
    ResolvePlaybackRequestDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_song_dto(self.song, serializer);
    sse_encode_audio_quality_dto(self.quality, serializer);
    sse_encode_bool(self.freePreview, serializer);
  }

  @protected
  void sse_encode_sdk_capabilities_dto(
    SdkCapabilitiesDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.platform, serializer);
    sse_encode_bool(self.songSearch, serializer);
    sse_encode_bool(self.dailyRecommendation, serializer);
    sse_encode_bool(self.rank, serializer);
    sse_encode_bool(self.trendingPlaylists, serializer);
    sse_encode_bool(self.lyrics, serializer);
    sse_encode_bool(self.qrAuth, serializer);
    sse_encode_bool(self.cloudLibrary, serializer);
  }

  @protected
  void sse_encode_search_page_dto(
    SearchPageDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_song_dto(self.items, serializer);
    sse_encode_u_32(self.page, serializer);
    sse_encode_u_32(self.pageSize, serializer);
    sse_encode_opt_CastedPrimitive_u_64(self.total, serializer);
  }

  @protected
  void sse_encode_search_songs_request_dto(
    SearchSongsRequestDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.keyword, serializer);
    sse_encode_u_32(self.page, serializer);
    sse_encode_u_32(self.pageSize, serializer);
  }

  @protected
  void sse_encode_song_dto(SongDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.artist, serializer);
    sse_encode_opt_String(self.album, serializer);
    sse_encode_opt_CastedPrimitive_u_64(self.durationSecs, serializer);
    sse_encode_opt_String(self.artworkUrl, serializer);
    sse_encode_opt_CastedPrimitive_i_64(self.privilege, serializer);
    sse_encode_opt_CastedPrimitive_u_64(self.albumId, serializer);
    sse_encode_opt_CastedPrimitive_u_64(self.mixSongId, serializer);
    sse_encode_audio_hashes_dto(self.hashes, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
