// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 1332007897;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__sdk__export_session_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "export_session",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, crate::api::sdk::BridgeError>(
                    (move || async move {
                        let output_ok = crate::api::sdk::export_session().await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__sdk__get_everyday_recommendations_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_everyday_recommendations",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, crate::api::sdk::BridgeError>(
                    (move || async move {
                        let output_ok = crate::api::sdk::get_everyday_recommendations().await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__sdk__get_sdk_capabilities_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_sdk_capabilities",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::sdk::get_sdk_capabilities())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__sdk__import_session_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "import_session",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_value = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, crate::api::sdk::BridgeError>(
                    (move || async move {
                        let output_ok = crate::api::sdk::import_session(api_value).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__sdk__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::sdk::init_app();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__sdk__initialize_sdk_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "initialize_sdk",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::sdk::BridgeError>((move || {
                    let output_ok = crate::api::sdk::initialize_sdk()?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__sdk__resolve_playback_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "resolve_playback",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request =
                <crate::api::sdk::ResolvePlaybackRequestDto>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, crate::api::sdk::BridgeError>(
                    (move || async move {
                        let output_ok = crate::api::sdk::resolve_playback(api_request).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__sdk__search_songs_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "search_songs",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request =
                <crate::api::sdk::SearchSongsRequestDto>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, crate::api::sdk::BridgeError>(
                    (move || async move {
                        let output_ok = crate::api::sdk::search_songs(api_request).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::sdk::AudioHashesDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_standard = <Option<String>>::sse_decode(deserializer);
        let mut var_high = <Option<String>>::sse_decode(deserializer);
        let mut var_flac = <Option<String>>::sse_decode(deserializer);
        let mut var_hiRes = <Option<String>>::sse_decode(deserializer);
        let mut var_superHash = <Option<String>>::sse_decode(deserializer);
        return crate::api::sdk::AudioHashesDto {
            standard: var_standard,
            high: var_high,
            flac: var_flac,
            hi_res: var_hiRes,
            super_hash: var_superHash,
        };
    }
}

impl SseDecode for crate::api::sdk::AudioQualityDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::sdk::AudioQualityDto::Standard,
            1 => crate::api::sdk::AudioQualityDto::High,
            2 => crate::api::sdk::AudioQualityDto::Flac,
            3 => crate::api::sdk::AudioQualityDto::HiRes,
            4 => crate::api::sdk::AudioQualityDto::Super,
            _ => unreachable!("Invalid variant for AudioQualityDto: {}", inner),
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::sdk::BridgeError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_kind = <crate::api::sdk::BridgeErrorKind>::sse_decode(deserializer);
        let mut var_message = <String>::sse_decode(deserializer);
        let mut var_code = <Option<i64>>::sse_decode(deserializer);
        let mut var_retryable = <bool>::sse_decode(deserializer);
        return crate::api::sdk::BridgeError {
            kind: var_kind,
            message: var_message,
            code: var_code,
            retryable: var_retryable,
        };
    }
}

impl SseDecode for crate::api::sdk::BridgeErrorKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::sdk::BridgeErrorKind::InvalidArgument,
            1 => crate::api::sdk::BridgeErrorKind::Transport,
            2 => crate::api::sdk::BridgeErrorKind::Upstream,
            3 => crate::api::sdk::BridgeErrorKind::AuthenticationRequired,
            4 => crate::api::sdk::BridgeErrorKind::SecurityChallenge,
            5 => crate::api::sdk::BridgeErrorKind::Unsupported,
            6 => crate::api::sdk::BridgeErrorKind::Internal,
            _ => unreachable!("Invalid variant for BridgeErrorKind: {}", inner),
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::sdk::SongDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::sdk::SongDto>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<i64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::sdk::PlaybackResolutionDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_url = <String>::sse_decode(deserializer);
                let mut var_bitRate = <Option<u64>>::sse_decode(deserializer);
                let mut var_durationSecs = <Option<u64>>::sse_decode(deserializer);
                return crate::api::sdk::PlaybackResolutionDto::Playable {
                    url: var_url,
                    bit_rate: var_bitRate,
                    duration_secs: var_durationSecs,
                };
            }
            1 => {
                let mut var_url = <String>::sse_decode(deserializer);
                let mut var_endMs = <Option<u64>>::sse_decode(deserializer);
                let mut var_bitRate = <Option<u64>>::sse_decode(deserializer);
                let mut var_durationSecs = <Option<u64>>::sse_decode(deserializer);
                return crate::api::sdk::PlaybackResolutionDto::Preview {
                    url: var_url,
                    end_ms: var_endMs,
                    bit_rate: var_bitRate,
                    duration_secs: var_durationSecs,
                };
            }
            2 => {
                let mut var_status = <Option<i64>>::sse_decode(deserializer);
                let mut var_failProcess = <Option<i64>>::sse_decode(deserializer);
                return crate::api::sdk::PlaybackResolutionDto::Denied {
                    status: var_status,
                    fail_process: var_failProcess,
                };
            }
            3 => {
                return crate::api::sdk::PlaybackResolutionDto::Unavailable;
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::sdk::RecommendationDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_title = <String>::sse_decode(deserializer);
        let mut var_subtitle = <Option<String>>::sse_decode(deserializer);
        let mut var_artworkUrl = <Option<String>>::sse_decode(deserializer);
        let mut var_creationDate = <Option<String>>::sse_decode(deserializer);
        let mut var_songs = <Vec<crate::api::sdk::SongDto>>::sse_decode(deserializer);
        return crate::api::sdk::RecommendationDto {
            title: var_title,
            subtitle: var_subtitle,
            artwork_url: var_artworkUrl,
            creation_date: var_creationDate,
            songs: var_songs,
        };
    }
}

impl SseDecode for crate::api::sdk::ResolvePlaybackRequestDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_song = <crate::api::sdk::SongDto>::sse_decode(deserializer);
        let mut var_quality = <crate::api::sdk::AudioQualityDto>::sse_decode(deserializer);
        let mut var_freePreview = <bool>::sse_decode(deserializer);
        return crate::api::sdk::ResolvePlaybackRequestDto {
            song: var_song,
            quality: var_quality,
            free_preview: var_freePreview,
        };
    }
}

impl SseDecode for crate::api::sdk::SdkCapabilitiesDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_platform = <String>::sse_decode(deserializer);
        let mut var_songSearch = <bool>::sse_decode(deserializer);
        let mut var_dailyRecommendation = <bool>::sse_decode(deserializer);
        let mut var_rank = <bool>::sse_decode(deserializer);
        let mut var_trendingPlaylists = <bool>::sse_decode(deserializer);
        let mut var_lyrics = <bool>::sse_decode(deserializer);
        let mut var_qrAuth = <bool>::sse_decode(deserializer);
        let mut var_cloudLibrary = <bool>::sse_decode(deserializer);
        return crate::api::sdk::SdkCapabilitiesDto {
            platform: var_platform,
            song_search: var_songSearch,
            daily_recommendation: var_dailyRecommendation,
            rank: var_rank,
            trending_playlists: var_trendingPlaylists,
            lyrics: var_lyrics,
            qr_auth: var_qrAuth,
            cloud_library: var_cloudLibrary,
        };
    }
}

impl SseDecode for crate::api::sdk::SearchPageDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_items = <Vec<crate::api::sdk::SongDto>>::sse_decode(deserializer);
        let mut var_page = <u32>::sse_decode(deserializer);
        let mut var_pageSize = <u32>::sse_decode(deserializer);
        let mut var_total = <Option<u64>>::sse_decode(deserializer);
        return crate::api::sdk::SearchPageDto {
            items: var_items,
            page: var_page,
            page_size: var_pageSize,
            total: var_total,
        };
    }
}

impl SseDecode for crate::api::sdk::SearchSongsRequestDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_keyword = <String>::sse_decode(deserializer);
        let mut var_page = <u32>::sse_decode(deserializer);
        let mut var_pageSize = <u32>::sse_decode(deserializer);
        return crate::api::sdk::SearchSongsRequestDto {
            keyword: var_keyword,
            page: var_page,
            page_size: var_pageSize,
        };
    }
}

impl SseDecode for crate::api::sdk::SongDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_title = <String>::sse_decode(deserializer);
        let mut var_artist = <Option<String>>::sse_decode(deserializer);
        let mut var_album = <Option<String>>::sse_decode(deserializer);
        let mut var_durationSecs = <Option<u64>>::sse_decode(deserializer);
        let mut var_artworkUrl = <Option<String>>::sse_decode(deserializer);
        let mut var_privilege = <Option<i64>>::sse_decode(deserializer);
        let mut var_albumId = <Option<u64>>::sse_decode(deserializer);
        let mut var_mixSongId = <Option<u64>>::sse_decode(deserializer);
        let mut var_hashes = <crate::api::sdk::AudioHashesDto>::sse_decode(deserializer);
        return crate::api::sdk::SongDto {
            id: var_id,
            title: var_title,
            artist: var_artist,
            album: var_album,
            duration_secs: var_durationSecs,
            artwork_url: var_artworkUrl,
            privilege: var_privilege,
            album_id: var_albumId,
            mix_song_id: var_mixSongId,
            hashes: var_hashes,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__sdk__export_session_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__api__sdk__get_everyday_recommendations_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        4 => wire__crate__api__sdk__import_session_impl(port, ptr, rust_vec_len, data_len),
        5 => wire__crate__api__sdk__init_app_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__api__sdk__initialize_sdk_impl(port, ptr, rust_vec_len, data_len),
        7 => wire__crate__api__sdk__resolve_playback_impl(port, ptr, rust_vec_len, data_len),
        8 => wire__crate__api__sdk__search_songs_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        3 => wire__crate__api__sdk__get_sdk_capabilities_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::sdk::AudioHashesDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.standard.into_into_dart().into_dart(),
            self.high.into_into_dart().into_dart(),
            self.flac.into_into_dart().into_dart(),
            self.hi_res.into_into_dart().into_dart(),
            self.super_hash.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::sdk::AudioHashesDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::sdk::AudioHashesDto>
    for crate::api::sdk::AudioHashesDto
{
    fn into_into_dart(self) -> crate::api::sdk::AudioHashesDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::sdk::AudioQualityDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Standard => 0.into_dart(),
            Self::High => 1.into_dart(),
            Self::Flac => 2.into_dart(),
            Self::HiRes => 3.into_dart(),
            Self::Super => 4.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::sdk::AudioQualityDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::sdk::AudioQualityDto>
    for crate::api::sdk::AudioQualityDto
{
    fn into_into_dart(self) -> crate::api::sdk::AudioQualityDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::sdk::BridgeError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.kind.into_into_dart().into_dart(),
            self.message.into_into_dart().into_dart(),
            self.code.into_into_dart().into_dart(),
            self.retryable.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::sdk::BridgeError {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::sdk::BridgeError>
    for crate::api::sdk::BridgeError
{
    fn into_into_dart(self) -> crate::api::sdk::BridgeError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::sdk::BridgeErrorKind {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::InvalidArgument => 0.into_dart(),
            Self::Transport => 1.into_dart(),
            Self::Upstream => 2.into_dart(),
            Self::AuthenticationRequired => 3.into_dart(),
            Self::SecurityChallenge => 4.into_dart(),
            Self::Unsupported => 5.into_dart(),
            Self::Internal => 6.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::sdk::BridgeErrorKind
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::sdk::BridgeErrorKind>
    for crate::api::sdk::BridgeErrorKind
{
    fn into_into_dart(self) -> crate::api::sdk::BridgeErrorKind {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::sdk::PlaybackResolutionDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::sdk::PlaybackResolutionDto::Playable {
                url,
                bit_rate,
                duration_secs,
            } => [
                0.into_dart(),
                url.into_into_dart().into_dart(),
                bit_rate.into_into_dart().into_dart(),
                duration_secs.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::sdk::PlaybackResolutionDto::Preview {
                url,
                end_ms,
                bit_rate,
                duration_secs,
            } => [
                1.into_dart(),
                url.into_into_dart().into_dart(),
                end_ms.into_into_dart().into_dart(),
                bit_rate.into_into_dart().into_dart(),
                duration_secs.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::sdk::PlaybackResolutionDto::Denied {
                status,
                fail_process,
            } => [
                2.into_dart(),
                status.into_into_dart().into_dart(),
                fail_process.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::sdk::PlaybackResolutionDto::Unavailable => [3.into_dart()].into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::sdk::PlaybackResolutionDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::sdk::PlaybackResolutionDto>
    for crate::api::sdk::PlaybackResolutionDto
{
    fn into_into_dart(self) -> crate::api::sdk::PlaybackResolutionDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::sdk::RecommendationDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.title.into_into_dart().into_dart(),
            self.subtitle.into_into_dart().into_dart(),
            self.artwork_url.into_into_dart().into_dart(),
            self.creation_date.into_into_dart().into_dart(),
            self.songs.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::sdk::RecommendationDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::sdk::RecommendationDto>
    for crate::api::sdk::RecommendationDto
{
    fn into_into_dart(self) -> crate::api::sdk::RecommendationDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::sdk::ResolvePlaybackRequestDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.song.into_into_dart().into_dart(),
            self.quality.into_into_dart().into_dart(),
            self.free_preview.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::sdk::ResolvePlaybackRequestDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::sdk::ResolvePlaybackRequestDto>
    for crate::api::sdk::ResolvePlaybackRequestDto
{
    fn into_into_dart(self) -> crate::api::sdk::ResolvePlaybackRequestDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::sdk::SdkCapabilitiesDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.platform.into_into_dart().into_dart(),
            self.song_search.into_into_dart().into_dart(),
            self.daily_recommendation.into_into_dart().into_dart(),
            self.rank.into_into_dart().into_dart(),
            self.trending_playlists.into_into_dart().into_dart(),
            self.lyrics.into_into_dart().into_dart(),
            self.qr_auth.into_into_dart().into_dart(),
            self.cloud_library.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::sdk::SdkCapabilitiesDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::sdk::SdkCapabilitiesDto>
    for crate::api::sdk::SdkCapabilitiesDto
{
    fn into_into_dart(self) -> crate::api::sdk::SdkCapabilitiesDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::sdk::SearchPageDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.items.into_into_dart().into_dart(),
            self.page.into_into_dart().into_dart(),
            self.page_size.into_into_dart().into_dart(),
            self.total.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::sdk::SearchPageDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::sdk::SearchPageDto>
    for crate::api::sdk::SearchPageDto
{
    fn into_into_dart(self) -> crate::api::sdk::SearchPageDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::sdk::SearchSongsRequestDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.keyword.into_into_dart().into_dart(),
            self.page.into_into_dart().into_dart(),
            self.page_size.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::sdk::SearchSongsRequestDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::sdk::SearchSongsRequestDto>
    for crate::api::sdk::SearchSongsRequestDto
{
    fn into_into_dart(self) -> crate::api::sdk::SearchSongsRequestDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::sdk::SongDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.title.into_into_dart().into_dart(),
            self.artist.into_into_dart().into_dart(),
            self.album.into_into_dart().into_dart(),
            self.duration_secs.into_into_dart().into_dart(),
            self.artwork_url.into_into_dart().into_dart(),
            self.privilege.into_into_dart().into_dart(),
            self.album_id.into_into_dart().into_dart(),
            self.mix_song_id.into_into_dart().into_dart(),
            self.hashes.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::sdk::SongDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::sdk::SongDto> for crate::api::sdk::SongDto {
    fn into_into_dart(self) -> crate::api::sdk::SongDto {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::sdk::AudioHashesDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<String>>::sse_encode(self.standard, serializer);
        <Option<String>>::sse_encode(self.high, serializer);
        <Option<String>>::sse_encode(self.flac, serializer);
        <Option<String>>::sse_encode(self.hi_res, serializer);
        <Option<String>>::sse_encode(self.super_hash, serializer);
    }
}

impl SseEncode for crate::api::sdk::AudioQualityDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::sdk::AudioQualityDto::Standard => 0,
                crate::api::sdk::AudioQualityDto::High => 1,
                crate::api::sdk::AudioQualityDto::Flac => 2,
                crate::api::sdk::AudioQualityDto::HiRes => 3,
                crate::api::sdk::AudioQualityDto::Super => 4,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::sdk::BridgeError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::sdk::BridgeErrorKind>::sse_encode(self.kind, serializer);
        <String>::sse_encode(self.message, serializer);
        <Option<i64>>::sse_encode(self.code, serializer);
        <bool>::sse_encode(self.retryable, serializer);
    }
}

impl SseEncode for crate::api::sdk::BridgeErrorKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::sdk::BridgeErrorKind::InvalidArgument => 0,
                crate::api::sdk::BridgeErrorKind::Transport => 1,
                crate::api::sdk::BridgeErrorKind::Upstream => 2,
                crate::api::sdk::BridgeErrorKind::AuthenticationRequired => 3,
                crate::api::sdk::BridgeErrorKind::SecurityChallenge => 4,
                crate::api::sdk::BridgeErrorKind::Unsupported => 5,
                crate::api::sdk::BridgeErrorKind::Internal => 6,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::sdk::SongDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::sdk::SongDto>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <i64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::sdk::PlaybackResolutionDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::sdk::PlaybackResolutionDto::Playable {
                url,
                bit_rate,
                duration_secs,
            } => {
                <i32>::sse_encode(0, serializer);
                <String>::sse_encode(url, serializer);
                <Option<u64>>::sse_encode(bit_rate, serializer);
                <Option<u64>>::sse_encode(duration_secs, serializer);
            }
            crate::api::sdk::PlaybackResolutionDto::Preview {
                url,
                end_ms,
                bit_rate,
                duration_secs,
            } => {
                <i32>::sse_encode(1, serializer);
                <String>::sse_encode(url, serializer);
                <Option<u64>>::sse_encode(end_ms, serializer);
                <Option<u64>>::sse_encode(bit_rate, serializer);
                <Option<u64>>::sse_encode(duration_secs, serializer);
            }
            crate::api::sdk::PlaybackResolutionDto::Denied {
                status,
                fail_process,
            } => {
                <i32>::sse_encode(2, serializer);
                <Option<i64>>::sse_encode(status, serializer);
                <Option<i64>>::sse_encode(fail_process, serializer);
            }
            crate::api::sdk::PlaybackResolutionDto::Unavailable => {
                <i32>::sse_encode(3, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::sdk::RecommendationDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.title, serializer);
        <Option<String>>::sse_encode(self.subtitle, serializer);
        <Option<String>>::sse_encode(self.artwork_url, serializer);
        <Option<String>>::sse_encode(self.creation_date, serializer);
        <Vec<crate::api::sdk::SongDto>>::sse_encode(self.songs, serializer);
    }
}

impl SseEncode for crate::api::sdk::ResolvePlaybackRequestDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::sdk::SongDto>::sse_encode(self.song, serializer);
        <crate::api::sdk::AudioQualityDto>::sse_encode(self.quality, serializer);
        <bool>::sse_encode(self.free_preview, serializer);
    }
}

impl SseEncode for crate::api::sdk::SdkCapabilitiesDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.platform, serializer);
        <bool>::sse_encode(self.song_search, serializer);
        <bool>::sse_encode(self.daily_recommendation, serializer);
        <bool>::sse_encode(self.rank, serializer);
        <bool>::sse_encode(self.trending_playlists, serializer);
        <bool>::sse_encode(self.lyrics, serializer);
        <bool>::sse_encode(self.qr_auth, serializer);
        <bool>::sse_encode(self.cloud_library, serializer);
    }
}

impl SseEncode for crate::api::sdk::SearchPageDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::api::sdk::SongDto>>::sse_encode(self.items, serializer);
        <u32>::sse_encode(self.page, serializer);
        <u32>::sse_encode(self.page_size, serializer);
        <Option<u64>>::sse_encode(self.total, serializer);
    }
}

impl SseEncode for crate::api::sdk::SearchSongsRequestDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.keyword, serializer);
        <u32>::sse_encode(self.page, serializer);
        <u32>::sse_encode(self.page_size, serializer);
    }
}

impl SseEncode for crate::api::sdk::SongDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.title, serializer);
        <Option<String>>::sse_encode(self.artist, serializer);
        <Option<String>>::sse_encode(self.album, serializer);
        <Option<u64>>::sse_encode(self.duration_secs, serializer);
        <Option<String>>::sse_encode(self.artwork_url, serializer);
        <Option<i64>>::sse_encode(self.privilege, serializer);
        <Option<u64>>::sse_encode(self.album_id, serializer);
        <Option<u64>>::sse_encode(self.mix_song_id, serializer);
        <crate::api::sdk::AudioHashesDto>::sse_encode(self.hashes, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;
