import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';

const _defaultManifest = 'native/kugou_bridge/Cargo.toml';
const _defaultOutput = 'THIRD_PARTY_RUST_NOTICES.txt';

Future<void> main(List<String> arguments) async {
  var manifestPath = _defaultManifest;
  var outputPath = _defaultOutput;

  for (var index = 0; index < arguments.length; index++) {
    switch (arguments[index]) {
      case '--manifest-path':
        manifestPath = _valueAfter(arguments, ++index, '--manifest-path');
        break;
      case '--output':
        outputPath = _valueAfter(arguments, ++index, '--output');
        break;
      case '--help':
      case '-h':
        stdout.writeln(
          'Usage: dart run tool/generate_rust_notices.dart '
          '[--manifest-path PATH] [--output PATH]',
        );
        return;
      default:
        stderr.writeln('Unknown argument: ${arguments[index]}');
        exitCode = 64;
        return;
    }
  }

  final metadataResult = await Process.run('cargo', [
    'metadata',
    '--format-version=1',
    '--locked',
    '--manifest-path',
    manifestPath,
  ], runInShell: Platform.isWindows);
  if (metadataResult.exitCode != 0) {
    stderr.write(metadataResult.stderr);
    exitCode = metadataResult.exitCode;
    return;
  }

  final metadata =
      jsonDecode(metadataResult.stdout as String) as Map<String, Object?>;
  final resolve = metadata['resolve']! as Map<String, Object?>;
  final resolvedIds = (resolve['nodes']! as List<Object?>)
      .cast<Map<String, Object?>>()
      .map((node) => node['id']! as String)
      .toSet();
  final packages =
      (metadata['packages']! as List<Object?>)
          .cast<Map<String, Object?>>()
          .where((package) => resolvedIds.contains(package['id']))
          .where((package) => package['source'] != null)
          .toList()
        ..sort((left, right) {
          final nameOrder = (left['name']! as String).compareTo(
            right['name']! as String,
          );
          return nameOrder != 0
              ? nameOrder
              : (left['version']! as String).compareTo(
                  right['version']! as String,
                );
        });

  final licenseTexts = <String, _LicenseText>{};
  final notices = <_PackageNotice>[];
  for (final package in packages) {
    final packageLicenseKeys = <String>[];
    final manifest = File(package['manifest_path']! as String);
    for (final file in _licenseFiles(package, manifest.parent)) {
      final contents = utf8
          .decode(file.readAsBytesSync(), allowMalformed: true)
          .replaceAll('\r\n', '\n')
          .trim();
      final key = sha256.convert(utf8.encode(contents)).toString();
      licenseTexts.putIfAbsent(
        key,
        () => _LicenseText(
          key: key,
          fileName: file.uri.pathSegments.last,
          contents: contents,
        ),
      );
      packageLicenseKeys.add(key);
    }
    notices.add(_PackageNotice(package, packageLicenseKeys));
  }

  final sortedLicenses = licenseTexts.values.toList()
    ..sort((left, right) => left.key.compareTo(right.key));
  final licenseLabels = <String, String>{};
  for (var index = 0; index < sortedLicenses.length; index++) {
    licenseLabels[sortedLicenses[index].key] = 'L${index + 1}';
  }

  final output = StringBuffer()
    ..writeln('KGMusic Rust third-party notices')
    ..writeln('================================')
    ..writeln()
    ..writeln('Generated by tool/generate_rust_notices.dart from Cargo.lock.')
    ..writeln(
      'Do not edit this file manually; regenerate it after Rust dependency changes.',
    )
    ..writeln(
      'KGMusic itself is excluded and is licensed under GPL-3.0-or-later.',
    )
    ..writeln();

  for (final notice in notices) {
    final package = notice.package;
    output
      ..writeln('${package['name']} ${package['version']}')
      ..writeln('  License: ${package['license'] ?? '(not declared)'}')
      ..writeln('  Source: ${package['source']}');
    final repository = package['repository'] as String?;
    if (repository != null && repository.isNotEmpty) {
      output.writeln('  Repository: $repository');
    }
    final labels = notice.licenseKeys
        .map((key) => licenseLabels[key]!)
        .toSet()
        .join(', ');
    output.writeln(
      '  License texts: ${labels.isEmpty ? '(none in crate archive)' : labels}',
    );
  }

  output
    ..writeln()
    ..writeln('License texts')
    ..writeln('=============')
    ..writeln();
  for (final license in sortedLicenses) {
    output
      ..writeln(
        '------------------------------------------------------------------------',
      )
      ..writeln('${licenseLabels[license.key]} (${license.fileName})')
      ..writeln()
      ..writeln(license.contents)
      ..writeln();
  }

  final outputFile = File(outputPath);
  outputFile.parent.createSync(recursive: true);
  outputFile.writeAsStringSync('${output.toString().trimRight()}\n');
}

String _valueAfter(List<String> arguments, int index, String option) {
  if (index >= arguments.length || arguments[index].startsWith('-')) {
    stderr.writeln('$option requires a value.');
    exit(64);
  }
  return arguments[index];
}

List<File> _licenseFiles(
  Map<String, Object?> package,
  Directory packageDirectory,
) {
  final files = <String, File>{};
  final declaredLicenseFile = package['license_file'] as String?;
  if (declaredLicenseFile != null && declaredLicenseFile.isNotEmpty) {
    final file = File(
      '${packageDirectory.path}${Platform.pathSeparator}$declaredLicenseFile',
    );
    if (file.existsSync()) files[file.absolute.path] = file;
  }

  final licenseName = RegExp(
    r'^(license|licence|copying|notice|unlicense|copyright)([._-].*)?$',
    caseSensitive: false,
  );
  for (final entity in packageDirectory.listSync(followLinks: false)) {
    if (entity is! File) continue;
    final name = entity.uri.pathSegments.last;
    if (licenseName.hasMatch(name)) files[entity.absolute.path] = entity;
  }

  final result = files.values.toList()
    ..sort((left, right) => left.path.compareTo(right.path));
  return result;
}

final class _PackageNotice {
  const _PackageNotice(this.package, this.licenseKeys);

  final Map<String, Object?> package;
  final List<String> licenseKeys;
}

final class _LicenseText {
  const _LicenseText({
    required this.key,
    required this.fileName,
    required this.contents,
  });

  final String key;
  final String fileName;
  final String contents;
}
