// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'dto.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class AudioHashesDto {
  final String? standard;
  final String? high;
  final String? flac;
  final String? hiRes;
  final String? superHash;

  const AudioHashesDto({
    this.standard,
    this.high,
    this.flac,
    this.hiRes,
    this.superHash,
  });

  static Future<AudioHashesDto> default_() =>
      RustLib.instance.api.crateApiDtoAudioHashesDtoDefault();

  @override
  int get hashCode =>
      standard.hashCode ^
      high.hashCode ^
      flac.hashCode ^
      hiRes.hashCode ^
      superHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioHashesDto &&
          runtimeType == other.runtimeType &&
          standard == other.standard &&
          high == other.high &&
          flac == other.flac &&
          hiRes == other.hiRes &&
          superHash == other.superHash;
}

enum AudioQualityDto { standard, high, flac, hiRes, super_ }

class AuthStateDto {
  final bool authenticated;
  final int? userId;
  final int? vipType;
  final bool fingerprintRegistered;

  const AuthStateDto({
    required this.authenticated,
    this.userId,
    this.vipType,
    required this.fingerprintRegistered,
  });

  @override
  int get hashCode =>
      authenticated.hashCode ^
      userId.hashCode ^
      vipType.hashCode ^
      fingerprintRegistered.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthStateDto &&
          runtimeType == other.runtimeType &&
          authenticated == other.authenticated &&
          userId == other.userId &&
          vipType == other.vipType &&
          fingerprintRegistered == other.fingerprintRegistered;
}

class BridgeError implements FrbException {
  final BridgeErrorKind kind;
  final String message;
  final int? code;
  final bool retryable;

  const BridgeError({
    required this.kind,
    required this.message,
    this.code,
    required this.retryable,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ message.hashCode ^ code.hashCode ^ retryable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message &&
          code == other.code &&
          retryable == other.retryable;
}

enum BridgeErrorKind {
  invalidArgument,
  sessionInvalid,
  transport,
  upstream,
  authenticationRequired,
  authenticationExpired,
  securityChallenge,
  unsupported,
  internal,
}

class CloudPlaylistDto {
  final int? listId;
  final String? globalCollectionId;
  final String name;
  final String? intro;
  final String? artworkUrl;
  final int? count;
  final int? listType;
  final int? creatorUserId;
  final String? creatorName;
  final bool isPrivate;
  final bool isMyFavorite;
  final bool isDefaultCollect;
  final String? tags;

  const CloudPlaylistDto({
    this.listId,
    this.globalCollectionId,
    required this.name,
    this.intro,
    this.artworkUrl,
    this.count,
    this.listType,
    this.creatorUserId,
    this.creatorName,
    required this.isPrivate,
    required this.isMyFavorite,
    required this.isDefaultCollect,
    this.tags,
  });

  @override
  int get hashCode =>
      listId.hashCode ^
      globalCollectionId.hashCode ^
      name.hashCode ^
      intro.hashCode ^
      artworkUrl.hashCode ^
      count.hashCode ^
      listType.hashCode ^
      creatorUserId.hashCode ^
      creatorName.hashCode ^
      isPrivate.hashCode ^
      isMyFavorite.hashCode ^
      isDefaultCollect.hashCode ^
      tags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CloudPlaylistDto &&
          runtimeType == other.runtimeType &&
          listId == other.listId &&
          globalCollectionId == other.globalCollectionId &&
          name == other.name &&
          intro == other.intro &&
          artworkUrl == other.artworkUrl &&
          count == other.count &&
          listType == other.listType &&
          creatorUserId == other.creatorUserId &&
          creatorName == other.creatorName &&
          isPrivate == other.isPrivate &&
          isMyFavorite == other.isMyFavorite &&
          isDefaultCollect == other.isDefaultCollect &&
          tags == other.tags;
}

class CloudPlaylistPageDto {
  final List<CloudPlaylistDto> items;
  final int page;
  final int pageSize;
  final int? total;

  const CloudPlaylistPageDto({
    required this.items,
    required this.page,
    required this.pageSize,
    this.total,
  });

  @override
  int get hashCode =>
      items.hashCode ^ page.hashCode ^ pageSize.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CloudPlaylistPageDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          page == other.page &&
          pageSize == other.pageSize &&
          total == other.total;
}

class DeviceProfileDto {
  final String deviceId;
  final String? androidId;
  final String? brand;
  final String? model;
  final String? manufacturer;
  final String? basebandVersion;
  final int? availableRamBytes;
  final int? availableInternalStorageBytes;
  final int? availableExternalStorageBytes;
  final int? batteryLevel;
  final int? batteryStatus;
  final bool hasAccelerometer;
  final bool hasGravity;
  final bool hasGyroscope;
  final bool hasLight;
  final bool hasMagneticField;
  final bool hasOrientation;
  final bool hasPressure;
  final bool hasStepCounter;
  final bool hasAmbientTemperature;

  const DeviceProfileDto({
    required this.deviceId,
    this.androidId,
    this.brand,
    this.model,
    this.manufacturer,
    this.basebandVersion,
    this.availableRamBytes,
    this.availableInternalStorageBytes,
    this.availableExternalStorageBytes,
    this.batteryLevel,
    this.batteryStatus,
    required this.hasAccelerometer,
    required this.hasGravity,
    required this.hasGyroscope,
    required this.hasLight,
    required this.hasMagneticField,
    required this.hasOrientation,
    required this.hasPressure,
    required this.hasStepCounter,
    required this.hasAmbientTemperature,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      androidId.hashCode ^
      brand.hashCode ^
      model.hashCode ^
      manufacturer.hashCode ^
      basebandVersion.hashCode ^
      availableRamBytes.hashCode ^
      availableInternalStorageBytes.hashCode ^
      availableExternalStorageBytes.hashCode ^
      batteryLevel.hashCode ^
      batteryStatus.hashCode ^
      hasAccelerometer.hashCode ^
      hasGravity.hashCode ^
      hasGyroscope.hashCode ^
      hasLight.hashCode ^
      hasMagneticField.hashCode ^
      hasOrientation.hashCode ^
      hasPressure.hashCode ^
      hasStepCounter.hashCode ^
      hasAmbientTemperature.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceProfileDto &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          androidId == other.androidId &&
          brand == other.brand &&
          model == other.model &&
          manufacturer == other.manufacturer &&
          basebandVersion == other.basebandVersion &&
          availableRamBytes == other.availableRamBytes &&
          availableInternalStorageBytes ==
              other.availableInternalStorageBytes &&
          availableExternalStorageBytes ==
              other.availableExternalStorageBytes &&
          batteryLevel == other.batteryLevel &&
          batteryStatus == other.batteryStatus &&
          hasAccelerometer == other.hasAccelerometer &&
          hasGravity == other.hasGravity &&
          hasGyroscope == other.hasGyroscope &&
          hasLight == other.hasLight &&
          hasMagneticField == other.hasMagneticField &&
          hasOrientation == other.hasOrientation &&
          hasPressure == other.hasPressure &&
          hasStepCounter == other.hasStepCounter &&
          hasAmbientTemperature == other.hasAmbientTemperature;
}

class HeartRadioRequestDto {
  final List<int> currentMixSongIds;

  const HeartRadioRequestDto({required this.currentMixSongIds});

  @override
  int get hashCode => currentMixSongIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HeartRadioRequestDto &&
          runtimeType == other.runtimeType &&
          currentMixSongIds == other.currentMixSongIds;
}

class HistoryPageDto {
  final List<HistorySongDto> items;
  final String? cursor;
  final bool hasMore;
  final int? total;

  const HistoryPageDto({
    required this.items,
    this.cursor,
    required this.hasMore,
    this.total,
  });

  @override
  int get hashCode =>
      items.hashCode ^ cursor.hashCode ^ hasMore.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistoryPageDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          cursor == other.cursor &&
          hasMore == other.hasMore &&
          total == other.total;
}

class HistorySongDto {
  final SongDto song;
  final int? playedAtSecs;
  final int? playCount;

  const HistorySongDto({required this.song, this.playedAtSecs, this.playCount});

  @override
  int get hashCode =>
      song.hashCode ^ playedAtSecs.hashCode ^ playCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistorySongDto &&
          runtimeType == other.runtimeType &&
          song == other.song &&
          playedAtSecs == other.playedAtSecs &&
          playCount == other.playCount;
}

class HistoryUploadItemDto {
  final int mixSongId;
  final int playedAtSecs;
  final int playCount;

  const HistoryUploadItemDto({
    required this.mixSongId,
    required this.playedAtSecs,
    required this.playCount,
  });

  @override
  int get hashCode =>
      mixSongId.hashCode ^ playedAtSecs.hashCode ^ playCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistoryUploadItemDto &&
          runtimeType == other.runtimeType &&
          mixSongId == other.mixSongId &&
          playedAtSecs == other.playedAtSecs &&
          playCount == other.playCount;
}

class LyricDocumentDto {
  final LyricFormatDto format;
  final int offsetMs;
  final List<LyricLineDto> lines;

  const LyricDocumentDto({
    required this.format,
    required this.offsetMs,
    required this.lines,
  });

  @override
  int get hashCode => format.hashCode ^ offsetMs.hashCode ^ lines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LyricDocumentDto &&
          runtimeType == other.runtimeType &&
          format == other.format &&
          offsetMs == other.offsetMs &&
          lines == other.lines;
}

@freezed
sealed class LyricFetchDto with _$LyricFetchDto {
  const LyricFetchDto._();

  const factory LyricFetchDto.found({required LyricDocumentDto document}) =
      LyricFetchDto_Found;
  const factory LyricFetchDto.notFound() = LyricFetchDto_NotFound;
}

enum LyricFormatDto { krc, lrc, plain }

class LyricLineDto {
  final int startMs;
  final int durationMs;
  final String text;
  final List<LyricWordDto> words;
  final String? translation;
  final String? transliteration;

  const LyricLineDto({
    required this.startMs,
    required this.durationMs,
    required this.text,
    required this.words,
    this.translation,
    this.transliteration,
  });

  @override
  int get hashCode =>
      startMs.hashCode ^
      durationMs.hashCode ^
      text.hashCode ^
      words.hashCode ^
      translation.hashCode ^
      transliteration.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LyricLineDto &&
          runtimeType == other.runtimeType &&
          startMs == other.startMs &&
          durationMs == other.durationMs &&
          text == other.text &&
          words == other.words &&
          translation == other.translation &&
          transliteration == other.transliteration;
}

class LyricWordDto {
  final int startMs;
  final int durationMs;
  final String text;

  const LyricWordDto({
    required this.startMs,
    required this.durationMs,
    required this.text,
  });

  @override
  int get hashCode => startMs.hashCode ^ durationMs.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LyricWordDto &&
          runtimeType == other.runtimeType &&
          startMs == other.startMs &&
          durationMs == other.durationMs &&
          text == other.text;
}

enum PersonalFmActionDto { play, skip, garbage }

class PersonalFmRequestDto {
  final PersonalFmActionDto action;
  final SongDto? currentSong;
  final int remainSongCount;
  final int? playtimeSecs;
  final String? markList;
  final String? currentMark;

  const PersonalFmRequestDto({
    required this.action,
    this.currentSong,
    required this.remainSongCount,
    this.playtimeSecs,
    this.markList,
    this.currentMark,
  });

  @override
  int get hashCode =>
      action.hashCode ^
      currentSong.hashCode ^
      remainSongCount.hashCode ^
      playtimeSecs.hashCode ^
      markList.hashCode ^
      currentMark.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PersonalFmRequestDto &&
          runtimeType == other.runtimeType &&
          action == other.action &&
          currentSong == other.currentSong &&
          remainSongCount == other.remainSongCount &&
          playtimeSecs == other.playtimeSecs &&
          markList == other.markList &&
          currentMark == other.currentMark;
}

@freezed
sealed class PlaybackResolutionDto with _$PlaybackResolutionDto {
  const PlaybackResolutionDto._();

  const factory PlaybackResolutionDto.playable({
    required String url,
    String? artworkUrl,
    required AudioQualityDto quality,
    int? bitRate,
    int? durationSecs,
  }) = PlaybackResolutionDto_Playable;
  const factory PlaybackResolutionDto.preview({
    required String url,
    String? artworkUrl,
    required AudioQualityDto quality,
    int? endMs,
    int? bitRate,
    int? durationSecs,
  }) = PlaybackResolutionDto_Preview;
  const factory PlaybackResolutionDto.denied() = PlaybackResolutionDto_Denied;
  const factory PlaybackResolutionDto.unavailable() =
      PlaybackResolutionDto_Unavailable;
}

class PlaylistEditInputDto {
  final int listId;
  final String? name;
  final bool? private;
  final String? intro;
  final String? tags;

  const PlaylistEditInputDto({
    required this.listId,
    this.name,
    this.private,
    this.intro,
    this.tags,
  });

  @override
  int get hashCode =>
      listId.hashCode ^
      name.hashCode ^
      private.hashCode ^
      intro.hashCode ^
      tags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistEditInputDto &&
          runtimeType == other.runtimeType &&
          listId == other.listId &&
          name == other.name &&
          private == other.private &&
          intro == other.intro &&
          tags == other.tags;
}

class PlaylistMutationDto {
  final int listId;
  final String? globalCollectionId;

  const PlaylistMutationDto({required this.listId, this.globalCollectionId});

  @override
  int get hashCode => listId.hashCode ^ globalCollectionId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistMutationDto &&
          runtimeType == other.runtimeType &&
          listId == other.listId &&
          globalCollectionId == other.globalCollectionId;
}

class PlaylistSearchHitDto {
  final int? specialId;
  final String? globalCollectionId;
  final String name;
  final String? intro;
  final String? artworkUrl;
  final int? songCount;
  final int? playCount;
  final int? collectCount;
  final String? creatorName;
  final int? creatorUserId;
  final String? tags;

  const PlaylistSearchHitDto({
    this.specialId,
    this.globalCollectionId,
    required this.name,
    this.intro,
    this.artworkUrl,
    this.songCount,
    this.playCount,
    this.collectCount,
    this.creatorName,
    this.creatorUserId,
    this.tags,
  });

  @override
  int get hashCode =>
      specialId.hashCode ^
      globalCollectionId.hashCode ^
      name.hashCode ^
      intro.hashCode ^
      artworkUrl.hashCode ^
      songCount.hashCode ^
      playCount.hashCode ^
      collectCount.hashCode ^
      creatorName.hashCode ^
      creatorUserId.hashCode ^
      tags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistSearchHitDto &&
          runtimeType == other.runtimeType &&
          specialId == other.specialId &&
          globalCollectionId == other.globalCollectionId &&
          name == other.name &&
          intro == other.intro &&
          artworkUrl == other.artworkUrl &&
          songCount == other.songCount &&
          playCount == other.playCount &&
          collectCount == other.collectCount &&
          creatorName == other.creatorName &&
          creatorUserId == other.creatorUserId &&
          tags == other.tags;
}

class PlaylistSearchPageDto {
  final List<PlaylistSearchHitDto> items;
  final int page;
  final int pageSize;
  final int? total;

  const PlaylistSearchPageDto({
    required this.items,
    required this.page,
    required this.pageSize,
    this.total,
  });

  @override
  int get hashCode =>
      items.hashCode ^ page.hashCode ^ pageSize.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistSearchPageDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          page == other.page &&
          pageSize == other.pageSize &&
          total == other.total;
}

class PlaylistTracksMutationDto {
  final List<int> fileIds;

  const PlaylistTracksMutationDto({required this.fileIds});

  @override
  int get hashCode => fileIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistTracksMutationDto &&
          runtimeType == other.runtimeType &&
          fileIds == other.fileIds;
}

class RecommendationBatchDto {
  final String title;
  final String? subtitle;
  final String? markList;
  final String? mark;
  final List<SongDto> songs;

  const RecommendationBatchDto({
    required this.title,
    this.subtitle,
    this.markList,
    this.mark,
    required this.songs,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      subtitle.hashCode ^
      markList.hashCode ^
      mark.hashCode ^
      songs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecommendationBatchDto &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          subtitle == other.subtitle &&
          markList == other.markList &&
          mark == other.mark &&
          songs == other.songs;
}

enum RecommendationHistoryActionDto { play, collect, trash }

class RecommendationHistoryItemDto {
  final RecommendationHistoryActionDto action;
  final SongDto song;

  const RecommendationHistoryItemDto({
    required this.action,
    required this.song,
  });

  @override
  int get hashCode => action.hashCode ^ song.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecommendationHistoryItemDto &&
          runtimeType == other.runtimeType &&
          action == other.action &&
          song == other.song;
}

class RecommendationReportAckDto {
  final int? syncPoint;
  final bool? isClean;

  const RecommendationReportAckDto({this.syncPoint, this.isClean});

  @override
  int get hashCode => syncPoint.hashCode ^ isClean.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecommendationReportAckDto &&
          runtimeType == other.runtimeType &&
          syncPoint == other.syncPoint &&
          isClean == other.isClean;
}

class ResolvePlaybackRequestDto {
  final SongDto song;
  final AudioQualityDto quality;
  final bool freePreview;

  const ResolvePlaybackRequestDto({
    required this.song,
    required this.quality,
    required this.freePreview,
  });

  @override
  int get hashCode => song.hashCode ^ quality.hashCode ^ freePreview.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResolvePlaybackRequestDto &&
          runtimeType == other.runtimeType &&
          song == other.song &&
          quality == other.quality &&
          freePreview == other.freePreview;
}

class SearchRequestDto {
  final String keyword;
  final int page;
  final int pageSize;

  const SearchRequestDto({
    required this.keyword,
    required this.page,
    required this.pageSize,
  });

  @override
  int get hashCode => keyword.hashCode ^ page.hashCode ^ pageSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchRequestDto &&
          runtimeType == other.runtimeType &&
          keyword == other.keyword &&
          page == other.page &&
          pageSize == other.pageSize;
}

class SmsLoginResultDto {
  final AuthStateDto auth;
  final String? fingerprintWarning;

  const SmsLoginResultDto({required this.auth, this.fingerprintWarning});

  @override
  int get hashCode => auth.hashCode ^ fingerprintWarning.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SmsLoginResultDto &&
          runtimeType == other.runtimeType &&
          auth == other.auth &&
          fingerprintWarning == other.fingerprintWarning;
}

class SongDto {
  final String id;
  final String title;
  final String? artist;
  final String? album;
  final int? durationSecs;
  final String? artworkUrl;
  final int? privilege;
  final int? albumId;
  final int? mixSongId;
  final int? fileId;
  final AudioHashesDto hashes;

  const SongDto({
    required this.id,
    required this.title,
    this.artist,
    this.album,
    this.durationSecs,
    this.artworkUrl,
    this.privilege,
    this.albumId,
    this.mixSongId,
    this.fileId,
    required this.hashes,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      durationSecs.hashCode ^
      artworkUrl.hashCode ^
      privilege.hashCode ^
      albumId.hashCode ^
      mixSongId.hashCode ^
      fileId.hashCode ^
      hashes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SongDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          durationSecs == other.durationSecs &&
          artworkUrl == other.artworkUrl &&
          privilege == other.privilege &&
          albumId == other.albumId &&
          mixSongId == other.mixSongId &&
          fileId == other.fileId &&
          hashes == other.hashes;
}

class SongPageDto {
  final List<SongDto> items;
  final int page;
  final int pageSize;
  final int? total;

  const SongPageDto({
    required this.items,
    required this.page,
    required this.pageSize,
    this.total,
  });

  @override
  int get hashCode =>
      items.hashCode ^ page.hashCode ^ pageSize.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SongPageDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          page == other.page &&
          pageSize == other.pageSize &&
          total == other.total;
}

class UserProfileDto {
  final int? userId;
  final String displayName;
  final String? username;
  final String? avatarUrl;
  final int? gender;
  final String? birthday;
  final String? city;
  final String? province;
  final String? signature;
  final int? followingCount;
  final int? fanCount;
  final int? visitorCount;

  const UserProfileDto({
    this.userId,
    required this.displayName,
    this.username,
    this.avatarUrl,
    this.gender,
    this.birthday,
    this.city,
    this.province,
    this.signature,
    this.followingCount,
    this.fanCount,
    this.visitorCount,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      displayName.hashCode ^
      username.hashCode ^
      avatarUrl.hashCode ^
      gender.hashCode ^
      birthday.hashCode ^
      city.hashCode ^
      province.hashCode ^
      signature.hashCode ^
      followingCount.hashCode ^
      fanCount.hashCode ^
      visitorCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserProfileDto &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          displayName == other.displayName &&
          username == other.username &&
          avatarUrl == other.avatarUrl &&
          gender == other.gender &&
          birthday == other.birthday &&
          city == other.city &&
          province == other.province &&
          signature == other.signature &&
          followingCount == other.followingCount &&
          fanCount == other.fanCount &&
          visitorCount == other.visitorCount;
}

class UserVipDto {
  final int? vipType;
  final int? musicPackageType;
  final int? yearlyType;
  final String? vipEndTime;
  final String? musicEndTime;
  final String? yearlyEndTime;
  final String? productType;
  final String? businessType;
  final List<VipProductDto> products;

  const UserVipDto({
    this.vipType,
    this.musicPackageType,
    this.yearlyType,
    this.vipEndTime,
    this.musicEndTime,
    this.yearlyEndTime,
    this.productType,
    this.businessType,
    required this.products,
  });

  @override
  int get hashCode =>
      vipType.hashCode ^
      musicPackageType.hashCode ^
      yearlyType.hashCode ^
      vipEndTime.hashCode ^
      musicEndTime.hashCode ^
      yearlyEndTime.hashCode ^
      productType.hashCode ^
      businessType.hashCode ^
      products.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserVipDto &&
          runtimeType == other.runtimeType &&
          vipType == other.vipType &&
          musicPackageType == other.musicPackageType &&
          yearlyType == other.yearlyType &&
          vipEndTime == other.vipEndTime &&
          musicEndTime == other.musicEndTime &&
          yearlyEndTime == other.yearlyEndTime &&
          productType == other.productType &&
          businessType == other.businessType &&
          products == other.products;
}

class VipClaimResultDto {
  final int? grantedUnits;
  final String? endTime;
  final int? serverTimeSecs;

  const VipClaimResultDto({
    this.grantedUnits,
    this.endTime,
    this.serverTimeSecs,
  });

  @override
  int get hashCode =>
      grantedUnits.hashCode ^ endTime.hashCode ^ serverTimeSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VipClaimResultDto &&
          runtimeType == other.runtimeType &&
          grantedUnits == other.grantedUnits &&
          endTime == other.endTime &&
          serverTimeSecs == other.serverTimeSecs;
}

class VipMonthRecordDto {
  final int? claimedDays;
  final List<String> claimDates;

  const VipMonthRecordDto({this.claimedDays, required this.claimDates});

  @override
  int get hashCode => claimedDays.hashCode ^ claimDates.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VipMonthRecordDto &&
          runtimeType == other.runtimeType &&
          claimedDays == other.claimedDays &&
          claimDates == other.claimDates;
}

class VipProductDto {
  final String? productType;
  final String? businessType;
  final bool active;
  final bool paid;
  final bool yearly;
  final String? vipEndTime;
  final String? paidExpireTime;

  const VipProductDto({
    this.productType,
    this.businessType,
    required this.active,
    required this.paid,
    required this.yearly,
    this.vipEndTime,
    this.paidExpireTime,
  });

  @override
  int get hashCode =>
      productType.hashCode ^
      businessType.hashCode ^
      active.hashCode ^
      paid.hashCode ^
      yearly.hashCode ^
      vipEndTime.hashCode ^
      paidExpireTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VipProductDto &&
          runtimeType == other.runtimeType &&
          productType == other.productType &&
          businessType == other.businessType &&
          active == other.active &&
          paid == other.paid &&
          yearly == other.yearly &&
          vipEndTime == other.vipEndTime &&
          paidExpireTime == other.paidExpireTime;
}

class VipUpgradeResultDto {
  final int? statusCode;
  final String? message;
  final String? endTime;

  const VipUpgradeResultDto({this.statusCode, this.message, this.endTime});

  @override
  int get hashCode => statusCode.hashCode ^ message.hashCode ^ endTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VipUpgradeResultDto &&
          runtimeType == other.runtimeType &&
          statusCode == other.statusCode &&
          message == other.message &&
          endTime == other.endTime;
}
