// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `auth_state`, `get_playlist_tracks`, `internal`, `invalid_argument`, `runtime`, `validated_search`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `KugouRuntime`, `PersistedSession`, `PlaylistTracksRoute`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `eq`, `fmt`, `fmt`

Future<void> initializeSdk() => RustLib.instance.api.crateApiSdkInitializeSdk();

Future<AuthStateDto> getAuthState() =>
    RustLib.instance.api.crateApiSdkGetAuthState();

Future<void> sendSmsCode({required String mobile}) =>
    RustLib.instance.api.crateApiSdkSendSmsCode(mobile: mobile);

Future<SmsLoginResultDto> loginBySms({
  required String mobile,
  required String code,
}) => RustLib.instance.api.crateApiSdkLoginBySms(mobile: mobile, code: code);

Future<AuthStateDto> refreshLogin() =>
    RustLib.instance.api.crateApiSdkRefreshLogin();

Future<AuthStateDto> registerDevice() =>
    RustLib.instance.api.crateApiSdkRegisterDevice();

Future<AuthStateDto> logout() => RustLib.instance.api.crateApiSdkLogout();

Future<SongPageDto> searchSongs({required SearchRequestDto request}) =>
    RustLib.instance.api.crateApiSdkSearchSongs(request: request);

Future<PlaylistSearchPageDto> searchPlaylists({
  required SearchRequestDto request,
}) => RustLib.instance.api.crateApiSdkSearchPlaylists(request: request);

Future<List<SongDto>> getEverydayRecommendations() =>
    RustLib.instance.api.crateApiSdkGetEverydayRecommendations();

Future<RecommendationBatchDto> getPersonalFm({
  required PersonalFmRequestDto request,
}) => RustLib.instance.api.crateApiSdkGetPersonalFm(request: request);

Future<RecommendationBatchDto> getHeartRadio({
  required HeartRadioRequestDto request,
}) => RustLib.instance.api.crateApiSdkGetHeartRadio(request: request);

Future<void> reportRecommendationHistory({
  required List<RecommendationHistoryItemDto> items,
}) => RustLib.instance.api.crateApiSdkReportRecommendationHistory(items: items);

Future<void> reportRecommendationRepeated({
  required List<String> hashes,
  required int remainSongCount,
}) => RustLib.instance.api.crateApiSdkReportRecommendationRepeated(
  hashes: hashes,
  remainSongCount: remainSongCount,
);

Future<void> reportRecommendationFavoriteClick({required SongDto song}) =>
    RustLib.instance.api.crateApiSdkReportRecommendationFavoriteClick(
      song: song,
    );

Future<PlaybackResolutionDto> resolvePlayback({
  required ResolvePlaybackRequestDto request,
}) => RustLib.instance.api.crateApiSdkResolvePlayback(request: request);

/// Fetch and parse the best timed lyric for a song.
///
/// Lyrics deliberately use the standard FileHash carried by `SongRef`; playback
/// quality hashes are not substituted. The candidate adjustment is applied to
/// the parsed document so Dart receives the final player timeline.
Future<LyricFetchDto> getSongLyrics({required SongDto song}) =>
    RustLib.instance.api.crateApiSdkGetSongLyrics(song: song);

Future<UserProfileDto> getUserProfile() =>
    RustLib.instance.api.crateApiSdkGetUserProfile();

Future<UserVipDto> getUserVip() => RustLib.instance.api.crateApiSdkGetUserVip();

Future<VipClaimResultDto> claimDayVip() =>
    RustLib.instance.api.crateApiSdkClaimDayVip();

Future<VipUpgradeResultDto> upgradeDayVip() =>
    RustLib.instance.api.crateApiSdkUpgradeDayVip();

Future<VipMonthRecordDto> getMonthVipRecord() =>
    RustLib.instance.api.crateApiSdkGetMonthVipRecord();

Future<HistoryPageDto> getCloudHistory({String? cursor}) =>
    RustLib.instance.api.crateApiSdkGetCloudHistory(cursor: cursor);

Future<void> uploadCloudHistory({required List<HistoryUploadItemDto> items}) =>
    RustLib.instance.api.crateApiSdkUploadCloudHistory(items: items);

Future<CloudPlaylistPageDto> getCloudPlaylists({
  required int page,
  required int pageSize,
}) => RustLib.instance.api.crateApiSdkGetCloudPlaylists(
  page: page,
  pageSize: pageSize,
);

Future<SongPageDto> getPlaylistTracksByGid({
  required String globalCollectionId,
  required int page,
  required int pageSize,
}) => RustLib.instance.api.crateApiSdkGetPlaylistTracksByGid(
  globalCollectionId: globalCollectionId,
  page: page,
  pageSize: pageSize,
);

Future<SongPageDto> getPlaylistTracksByListId({
  required int listId,
  required int page,
  required int pageSize,
}) => RustLib.instance.api.crateApiSdkGetPlaylistTracksByListId(
  listId: listId,
  page: page,
  pageSize: pageSize,
);

Future<PlaylistMutationDto> createCloudPlaylist({
  required String name,
  required bool private,
}) => RustLib.instance.api.crateApiSdkCreateCloudPlaylist(
  name: name,
  private: private,
);

Future<PlaylistMutationDto> collectCloudPlaylist({
  required String globalCollectionId,
  int? ownerUserId,
  String? name,
}) => RustLib.instance.api.crateApiSdkCollectCloudPlaylist(
  globalCollectionId: globalCollectionId,
  ownerUserId: ownerUserId,
  name: name,
);

Future<void> deleteCloudPlaylist({
  required int listId,
  required bool collected,
}) => RustLib.instance.api.crateApiSdkDeleteCloudPlaylist(
  listId: listId,
  collected: collected,
);

Future<void> editCloudPlaylist({required PlaylistEditInputDto input}) =>
    RustLib.instance.api.crateApiSdkEditCloudPlaylist(input: input);

Future<PlaylistTracksMutationDto> addSongToPlaylist({
  required int listId,
  required SongDto song,
}) => RustLib.instance.api.crateApiSdkAddSongToPlaylist(
  listId: listId,
  song: song,
);

Future<void> removeSongFromPlaylist({
  required int listId,
  required int fileId,
}) => RustLib.instance.api.crateApiSdkRemoveSongFromPlaylist(
  listId: listId,
  fileId: fileId,
);

Future<String> exportSession() =>
    RustLib.instance.api.crateApiSdkExportSession();

Future<void> importSession({required String value}) =>
    RustLib.instance.api.crateApiSdkImportSession(value: value);
