// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'sdk.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `artwork_from_extra`, `artwork_from_object`, `artwork_from_value`, `artwork_key_matches`, `audio_hashes_from_detail`, `audio_quality_to_dto`, `auth_state`, `bool_for_keys`, `cloud_playlist_to_dto`, `collect_detail_enrichment`, `from_sdk`, `internal`, `invalid_argument`, `nonempty_artwork`, `object_value_for_key`, `playlist_tracks_route`, `runtime`, `scalar_string_for_keys`, `search_playlist_to_dto`, `select_hash`, `song_to_dto_with_enrichment`, `songs_to_dtos_with_artwork`, `stable_song_id`, `string_for_keys`, `validated_search`, `value_u64_for_keys`, `vip_product_to_dto`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `KugouRuntime`, `PersistedSession`, `PlaylistTracksRoute`, `SongDetailEnrichment`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

Future<SdkCapabilitiesDto> initializeSdk() =>
    RustLib.instance.api.crateApiSdkInitializeSdk();

SdkCapabilitiesDto getSdkCapabilities() =>
    RustLib.instance.api.crateApiSdkGetSdkCapabilities();

Future<AuthStateDto> getAuthState() =>
    RustLib.instance.api.crateApiSdkGetAuthState();

Future<void> sendSmsCode({required String mobile}) =>
    RustLib.instance.api.crateApiSdkSendSmsCode(mobile: mobile);

Future<SmsLoginResultDto> loginBySms({
  required String mobile,
  required String code,
}) => RustLib.instance.api.crateApiSdkLoginBySms(mobile: mobile, code: code);

Future<AuthStateDto> refreshLogin() =>
    RustLib.instance.api.crateApiSdkRefreshLogin();

Future<AuthStateDto> registerDevice() =>
    RustLib.instance.api.crateApiSdkRegisterDevice();

Future<AuthStateDto> logout() => RustLib.instance.api.crateApiSdkLogout();

Future<SongPageDto> searchSongs({required SearchRequestDto request}) =>
    RustLib.instance.api.crateApiSdkSearchSongs(request: request);

Future<PlaylistSearchPageDto> searchPlaylists({
  required SearchRequestDto request,
}) => RustLib.instance.api.crateApiSdkSearchPlaylists(request: request);

Future<RecommendationDto> getEverydayRecommendations() =>
    RustLib.instance.api.crateApiSdkGetEverydayRecommendations();

Future<PlaybackResolutionDto> resolvePlayback({
  required ResolvePlaybackRequestDto request,
}) => RustLib.instance.api.crateApiSdkResolvePlayback(request: request);

Future<UserProfileDto> getUserProfile() =>
    RustLib.instance.api.crateApiSdkGetUserProfile();

Future<UserVipDto> getUserVip() => RustLib.instance.api.crateApiSdkGetUserVip();

Future<VipClaimResultDto> claimDayVip() =>
    RustLib.instance.api.crateApiSdkClaimDayVip();

Future<VipUpgradeResultDto> upgradeDayVip() =>
    RustLib.instance.api.crateApiSdkUpgradeDayVip();

Future<VipMonthRecordDto> getMonthVipRecord() =>
    RustLib.instance.api.crateApiSdkGetMonthVipRecord();

Future<HistoryPageDto> getCloudHistory({String? cursor}) =>
    RustLib.instance.api.crateApiSdkGetCloudHistory(cursor: cursor);

Future<void> uploadCloudHistory({required List<HistoryUploadItemDto> items}) =>
    RustLib.instance.api.crateApiSdkUploadCloudHistory(items: items);

Future<CloudPlaylistPageDto> getCloudPlaylists({
  required int page,
  required int pageSize,
}) => RustLib.instance.api.crateApiSdkGetCloudPlaylists(
  page: page,
  pageSize: pageSize,
);

Future<SongPageDto> getPlaylistTracks({
  required PlaylistTracksRequestDto request,
}) => RustLib.instance.api.crateApiSdkGetPlaylistTracks(request: request);

Future<PlaylistMutationDto> createCloudPlaylist({
  required String name,
  required bool private,
}) => RustLib.instance.api.crateApiSdkCreateCloudPlaylist(
  name: name,
  private: private,
);

Future<PlaylistMutationDto> collectCloudPlaylist({
  required String globalCollectionId,
  int? ownerUserId,
  String? name,
}) => RustLib.instance.api.crateApiSdkCollectCloudPlaylist(
  globalCollectionId: globalCollectionId,
  ownerUserId: ownerUserId,
  name: name,
);

Future<void> deleteCloudPlaylist({
  required int listId,
  required bool collected,
}) => RustLib.instance.api.crateApiSdkDeleteCloudPlaylist(
  listId: listId,
  collected: collected,
);

Future<void> editCloudPlaylist({required PlaylistEditInputDto input}) =>
    RustLib.instance.api.crateApiSdkEditCloudPlaylist(input: input);

Future<PlaylistTracksMutationDto> addSongToPlaylist({
  required int listId,
  required SongDto song,
}) => RustLib.instance.api.crateApiSdkAddSongToPlaylist(
  listId: listId,
  song: song,
);

Future<void> removeSongFromPlaylist({
  required int listId,
  required int fileId,
}) => RustLib.instance.api.crateApiSdkRemoveSongFromPlaylist(
  listId: listId,
  fileId: fileId,
);

Future<String> exportSession() =>
    RustLib.instance.api.crateApiSdkExportSession();

Future<void> importSession({required String value}) =>
    RustLib.instance.api.crateApiSdkImportSession(value: value);

class AudioHashesDto {
  final String? standard;
  final String? high;
  final String? flac;
  final String? hiRes;
  final String? superHash;

  const AudioHashesDto({
    this.standard,
    this.high,
    this.flac,
    this.hiRes,
    this.superHash,
  });

  static Future<AudioHashesDto> default_() =>
      RustLib.instance.api.crateApiSdkAudioHashesDtoDefault();

  @override
  int get hashCode =>
      standard.hashCode ^
      high.hashCode ^
      flac.hashCode ^
      hiRes.hashCode ^
      superHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioHashesDto &&
          runtimeType == other.runtimeType &&
          standard == other.standard &&
          high == other.high &&
          flac == other.flac &&
          hiRes == other.hiRes &&
          superHash == other.superHash;
}

enum AudioQualityDto { standard, high, flac, hiRes, super_ }

class AuthStateDto {
  final bool authenticated;
  final int? userId;
  final int? vipType;
  final bool fingerprintRegistered;

  const AuthStateDto({
    required this.authenticated,
    this.userId,
    this.vipType,
    required this.fingerprintRegistered,
  });

  @override
  int get hashCode =>
      authenticated.hashCode ^
      userId.hashCode ^
      vipType.hashCode ^
      fingerprintRegistered.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthStateDto &&
          runtimeType == other.runtimeType &&
          authenticated == other.authenticated &&
          userId == other.userId &&
          vipType == other.vipType &&
          fingerprintRegistered == other.fingerprintRegistered;
}

class BridgeError implements FrbException {
  final BridgeErrorKind kind;
  final String message;
  final int? code;
  final bool retryable;

  const BridgeError({
    required this.kind,
    required this.message,
    this.code,
    required this.retryable,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ message.hashCode ^ code.hashCode ^ retryable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message &&
          code == other.code &&
          retryable == other.retryable;
}

enum BridgeErrorKind {
  invalidArgument,
  transport,
  upstream,
  authenticationRequired,
  authenticationExpired,
  securityChallenge,
  unsupported,
  internal,
}

class CloudPlaylistDto {
  final int? listId;
  final String? globalCollectionId;
  final String name;
  final String? intro;
  final String? artworkUrl;
  final int? count;
  final int? listType;
  final int? creatorUserId;
  final String? creatorName;
  final bool isPrivate;
  final bool isMyFavorite;
  final bool isDefaultCollect;
  final String? tags;

  const CloudPlaylistDto({
    this.listId,
    this.globalCollectionId,
    required this.name,
    this.intro,
    this.artworkUrl,
    this.count,
    this.listType,
    this.creatorUserId,
    this.creatorName,
    required this.isPrivate,
    required this.isMyFavorite,
    required this.isDefaultCollect,
    this.tags,
  });

  @override
  int get hashCode =>
      listId.hashCode ^
      globalCollectionId.hashCode ^
      name.hashCode ^
      intro.hashCode ^
      artworkUrl.hashCode ^
      count.hashCode ^
      listType.hashCode ^
      creatorUserId.hashCode ^
      creatorName.hashCode ^
      isPrivate.hashCode ^
      isMyFavorite.hashCode ^
      isDefaultCollect.hashCode ^
      tags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CloudPlaylistDto &&
          runtimeType == other.runtimeType &&
          listId == other.listId &&
          globalCollectionId == other.globalCollectionId &&
          name == other.name &&
          intro == other.intro &&
          artworkUrl == other.artworkUrl &&
          count == other.count &&
          listType == other.listType &&
          creatorUserId == other.creatorUserId &&
          creatorName == other.creatorName &&
          isPrivate == other.isPrivate &&
          isMyFavorite == other.isMyFavorite &&
          isDefaultCollect == other.isDefaultCollect &&
          tags == other.tags;
}

class CloudPlaylistPageDto {
  final List<CloudPlaylistDto> items;
  final int page;
  final int pageSize;
  final int? total;
  final int? totalVersion;

  const CloudPlaylistPageDto({
    required this.items,
    required this.page,
    required this.pageSize,
    this.total,
    this.totalVersion,
  });

  @override
  int get hashCode =>
      items.hashCode ^
      page.hashCode ^
      pageSize.hashCode ^
      total.hashCode ^
      totalVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CloudPlaylistPageDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          page == other.page &&
          pageSize == other.pageSize &&
          total == other.total &&
          totalVersion == other.totalVersion;
}

class HistoryPageDto {
  final List<HistorySongDto> items;
  final String? cursor;
  final bool hasMore;
  final int? total;

  const HistoryPageDto({
    required this.items,
    this.cursor,
    required this.hasMore,
    this.total,
  });

  @override
  int get hashCode =>
      items.hashCode ^ cursor.hashCode ^ hasMore.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistoryPageDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          cursor == other.cursor &&
          hasMore == other.hasMore &&
          total == other.total;
}

class HistorySongDto {
  final SongDto song;
  final int? playedAtSecs;
  final int? playCount;

  const HistorySongDto({required this.song, this.playedAtSecs, this.playCount});

  @override
  int get hashCode =>
      song.hashCode ^ playedAtSecs.hashCode ^ playCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistorySongDto &&
          runtimeType == other.runtimeType &&
          song == other.song &&
          playedAtSecs == other.playedAtSecs &&
          playCount == other.playCount;
}

class HistoryUploadItemDto {
  final int mixSongId;
  final int playedAtSecs;
  final int playCount;

  const HistoryUploadItemDto({
    required this.mixSongId,
    required this.playedAtSecs,
    required this.playCount,
  });

  @override
  int get hashCode =>
      mixSongId.hashCode ^ playedAtSecs.hashCode ^ playCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistoryUploadItemDto &&
          runtimeType == other.runtimeType &&
          mixSongId == other.mixSongId &&
          playedAtSecs == other.playedAtSecs &&
          playCount == other.playCount;
}

@freezed
sealed class PlaybackResolutionDto with _$PlaybackResolutionDto {
  const PlaybackResolutionDto._();

  const factory PlaybackResolutionDto.playable({
    required String url,
    String? artworkUrl,
    required AudioQualityDto quality,
    int? bitRate,
    int? durationSecs,
  }) = PlaybackResolutionDto_Playable;
  const factory PlaybackResolutionDto.preview({
    required String url,
    String? artworkUrl,
    required AudioQualityDto quality,
    int? endMs,
    int? bitRate,
    int? durationSecs,
  }) = PlaybackResolutionDto_Preview;
  const factory PlaybackResolutionDto.denied({int? status, int? failProcess}) =
      PlaybackResolutionDto_Denied;
  const factory PlaybackResolutionDto.unavailable() =
      PlaybackResolutionDto_Unavailable;
}

class PlaylistEditInputDto {
  final int listId;
  final String? name;
  final bool? private;
  final String? intro;
  final String? tags;
  final int? totalVersion;

  const PlaylistEditInputDto({
    required this.listId,
    this.name,
    this.private,
    this.intro,
    this.tags,
    this.totalVersion,
  });

  @override
  int get hashCode =>
      listId.hashCode ^
      name.hashCode ^
      private.hashCode ^
      intro.hashCode ^
      tags.hashCode ^
      totalVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistEditInputDto &&
          runtimeType == other.runtimeType &&
          listId == other.listId &&
          name == other.name &&
          private == other.private &&
          intro == other.intro &&
          tags == other.tags &&
          totalVersion == other.totalVersion;
}

class PlaylistMutationDto {
  final int? listId;
  final String? globalCollectionId;
  final String? name;

  const PlaylistMutationDto({this.listId, this.globalCollectionId, this.name});

  @override
  int get hashCode =>
      listId.hashCode ^ globalCollectionId.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistMutationDto &&
          runtimeType == other.runtimeType &&
          listId == other.listId &&
          globalCollectionId == other.globalCollectionId &&
          name == other.name;
}

class PlaylistSearchHitDto {
  final int? specialId;
  final String? globalCollectionId;
  final String name;
  final String? intro;
  final String? artworkUrl;
  final int? songCount;
  final int? playCount;
  final int? collectCount;
  final String? creatorName;
  final int? creatorUserId;
  final String? tags;

  const PlaylistSearchHitDto({
    this.specialId,
    this.globalCollectionId,
    required this.name,
    this.intro,
    this.artworkUrl,
    this.songCount,
    this.playCount,
    this.collectCount,
    this.creatorName,
    this.creatorUserId,
    this.tags,
  });

  @override
  int get hashCode =>
      specialId.hashCode ^
      globalCollectionId.hashCode ^
      name.hashCode ^
      intro.hashCode ^
      artworkUrl.hashCode ^
      songCount.hashCode ^
      playCount.hashCode ^
      collectCount.hashCode ^
      creatorName.hashCode ^
      creatorUserId.hashCode ^
      tags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistSearchHitDto &&
          runtimeType == other.runtimeType &&
          specialId == other.specialId &&
          globalCollectionId == other.globalCollectionId &&
          name == other.name &&
          intro == other.intro &&
          artworkUrl == other.artworkUrl &&
          songCount == other.songCount &&
          playCount == other.playCount &&
          collectCount == other.collectCount &&
          creatorName == other.creatorName &&
          creatorUserId == other.creatorUserId &&
          tags == other.tags;
}

class PlaylistSearchPageDto {
  final List<PlaylistSearchHitDto> items;
  final int page;
  final int pageSize;
  final int? total;

  const PlaylistSearchPageDto({
    required this.items,
    required this.page,
    required this.pageSize,
    this.total,
  });

  @override
  int get hashCode =>
      items.hashCode ^ page.hashCode ^ pageSize.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistSearchPageDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          page == other.page &&
          pageSize == other.pageSize &&
          total == other.total;
}

class PlaylistTracksMutationDto {
  final List<int> fileIds;

  const PlaylistTracksMutationDto({required this.fileIds});

  @override
  int get hashCode => fileIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistTracksMutationDto &&
          runtimeType == other.runtimeType &&
          fileIds == other.fileIds;
}

class PlaylistTracksRequestDto {
  final int? listId;
  final String? globalCollectionId;

  /// Prefer gid path when `global_collection_id` is set (newest-first).
  /// `owned` only selects `tracks_by_listid` when **no** gid is available
  /// (oldest-first physical order). Callers should pass gid for UI lists.
  final bool owned;
  final int page;
  final int pageSize;

  const PlaylistTracksRequestDto({
    this.listId,
    this.globalCollectionId,
    required this.owned,
    required this.page,
    required this.pageSize,
  });

  @override
  int get hashCode =>
      listId.hashCode ^
      globalCollectionId.hashCode ^
      owned.hashCode ^
      page.hashCode ^
      pageSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistTracksRequestDto &&
          runtimeType == other.runtimeType &&
          listId == other.listId &&
          globalCollectionId == other.globalCollectionId &&
          owned == other.owned &&
          page == other.page &&
          pageSize == other.pageSize;
}

class RecommendationDto {
  final String title;
  final String? subtitle;
  final String? artworkUrl;
  final String? creationDate;
  final List<SongDto> songs;

  const RecommendationDto({
    required this.title,
    this.subtitle,
    this.artworkUrl,
    this.creationDate,
    required this.songs,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      subtitle.hashCode ^
      artworkUrl.hashCode ^
      creationDate.hashCode ^
      songs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecommendationDto &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          subtitle == other.subtitle &&
          artworkUrl == other.artworkUrl &&
          creationDate == other.creationDate &&
          songs == other.songs;
}

class ResolvePlaybackRequestDto {
  final SongDto song;
  final AudioQualityDto quality;
  final bool freePreview;

  const ResolvePlaybackRequestDto({
    required this.song,
    required this.quality,
    required this.freePreview,
  });

  @override
  int get hashCode => song.hashCode ^ quality.hashCode ^ freePreview.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResolvePlaybackRequestDto &&
          runtimeType == other.runtimeType &&
          song == other.song &&
          quality == other.quality &&
          freePreview == other.freePreview;
}

class SdkCapabilitiesDto {
  final String platform;
  final bool songSearch;
  final bool playlistSearch;
  final bool dailyRecommendation;
  final bool smsAuth;
  final bool cloudLibrary;
  final bool playlistMutations;

  const SdkCapabilitiesDto({
    required this.platform,
    required this.songSearch,
    required this.playlistSearch,
    required this.dailyRecommendation,
    required this.smsAuth,
    required this.cloudLibrary,
    required this.playlistMutations,
  });

  @override
  int get hashCode =>
      platform.hashCode ^
      songSearch.hashCode ^
      playlistSearch.hashCode ^
      dailyRecommendation.hashCode ^
      smsAuth.hashCode ^
      cloudLibrary.hashCode ^
      playlistMutations.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SdkCapabilitiesDto &&
          runtimeType == other.runtimeType &&
          platform == other.platform &&
          songSearch == other.songSearch &&
          playlistSearch == other.playlistSearch &&
          dailyRecommendation == other.dailyRecommendation &&
          smsAuth == other.smsAuth &&
          cloudLibrary == other.cloudLibrary &&
          playlistMutations == other.playlistMutations;
}

class SearchRequestDto {
  final String keyword;
  final int page;
  final int pageSize;

  const SearchRequestDto({
    required this.keyword,
    required this.page,
    required this.pageSize,
  });

  @override
  int get hashCode => keyword.hashCode ^ page.hashCode ^ pageSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchRequestDto &&
          runtimeType == other.runtimeType &&
          keyword == other.keyword &&
          page == other.page &&
          pageSize == other.pageSize;
}

class SmsLoginResultDto {
  final AuthStateDto auth;
  final String? fingerprintWarning;

  const SmsLoginResultDto({required this.auth, this.fingerprintWarning});

  @override
  int get hashCode => auth.hashCode ^ fingerprintWarning.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SmsLoginResultDto &&
          runtimeType == other.runtimeType &&
          auth == other.auth &&
          fingerprintWarning == other.fingerprintWarning;
}

class SongDto {
  final String id;
  final String title;
  final String? artist;
  final String? album;
  final int? durationSecs;
  final String? artworkUrl;
  final int? privilege;
  final int? albumId;
  final int? mixSongId;
  final int? fileId;
  final AudioHashesDto hashes;

  const SongDto({
    required this.id,
    required this.title,
    this.artist,
    this.album,
    this.durationSecs,
    this.artworkUrl,
    this.privilege,
    this.albumId,
    this.mixSongId,
    this.fileId,
    required this.hashes,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      durationSecs.hashCode ^
      artworkUrl.hashCode ^
      privilege.hashCode ^
      albumId.hashCode ^
      mixSongId.hashCode ^
      fileId.hashCode ^
      hashes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SongDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          durationSecs == other.durationSecs &&
          artworkUrl == other.artworkUrl &&
          privilege == other.privilege &&
          albumId == other.albumId &&
          mixSongId == other.mixSongId &&
          fileId == other.fileId &&
          hashes == other.hashes;
}

class SongPageDto {
  final List<SongDto> items;
  final int page;
  final int pageSize;
  final int? total;

  const SongPageDto({
    required this.items,
    required this.page,
    required this.pageSize,
    this.total,
  });

  @override
  int get hashCode =>
      items.hashCode ^ page.hashCode ^ pageSize.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SongPageDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          page == other.page &&
          pageSize == other.pageSize &&
          total == other.total;
}

class UserProfileDto {
  final int? userId;
  final String displayName;
  final String? username;
  final String? avatarUrl;
  final int? gender;
  final String? birthday;
  final String? city;
  final String? province;
  final String? signature;
  final int? followingCount;
  final int? fanCount;
  final int? visitorCount;

  const UserProfileDto({
    this.userId,
    required this.displayName,
    this.username,
    this.avatarUrl,
    this.gender,
    this.birthday,
    this.city,
    this.province,
    this.signature,
    this.followingCount,
    this.fanCount,
    this.visitorCount,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      displayName.hashCode ^
      username.hashCode ^
      avatarUrl.hashCode ^
      gender.hashCode ^
      birthday.hashCode ^
      city.hashCode ^
      province.hashCode ^
      signature.hashCode ^
      followingCount.hashCode ^
      fanCount.hashCode ^
      visitorCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserProfileDto &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          displayName == other.displayName &&
          username == other.username &&
          avatarUrl == other.avatarUrl &&
          gender == other.gender &&
          birthday == other.birthday &&
          city == other.city &&
          province == other.province &&
          signature == other.signature &&
          followingCount == other.followingCount &&
          fanCount == other.fanCount &&
          visitorCount == other.visitorCount;
}

class UserVipDto {
  final int? vipType;
  final int? musicPackageType;
  final int? yearlyType;
  final String? vipEndTime;
  final String? musicEndTime;
  final String? yearlyEndTime;
  final String? productType;
  final String? businessType;
  final List<VipProductDto> products;

  const UserVipDto({
    this.vipType,
    this.musicPackageType,
    this.yearlyType,
    this.vipEndTime,
    this.musicEndTime,
    this.yearlyEndTime,
    this.productType,
    this.businessType,
    required this.products,
  });

  @override
  int get hashCode =>
      vipType.hashCode ^
      musicPackageType.hashCode ^
      yearlyType.hashCode ^
      vipEndTime.hashCode ^
      musicEndTime.hashCode ^
      yearlyEndTime.hashCode ^
      productType.hashCode ^
      businessType.hashCode ^
      products.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserVipDto &&
          runtimeType == other.runtimeType &&
          vipType == other.vipType &&
          musicPackageType == other.musicPackageType &&
          yearlyType == other.yearlyType &&
          vipEndTime == other.vipEndTime &&
          musicEndTime == other.musicEndTime &&
          yearlyEndTime == other.yearlyEndTime &&
          productType == other.productType &&
          businessType == other.businessType &&
          products == other.products;
}

class VipClaimResultDto {
  final int? grantedUnits;
  final String? endTime;
  final int? serverTimeSecs;

  const VipClaimResultDto({
    this.grantedUnits,
    this.endTime,
    this.serverTimeSecs,
  });

  @override
  int get hashCode =>
      grantedUnits.hashCode ^ endTime.hashCode ^ serverTimeSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VipClaimResultDto &&
          runtimeType == other.runtimeType &&
          grantedUnits == other.grantedUnits &&
          endTime == other.endTime &&
          serverTimeSecs == other.serverTimeSecs;
}

class VipMonthRecordDto {
  final int? claimedDays;
  final List<String> claimDates;

  const VipMonthRecordDto({this.claimedDays, required this.claimDates});

  @override
  int get hashCode => claimedDays.hashCode ^ claimDates.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VipMonthRecordDto &&
          runtimeType == other.runtimeType &&
          claimedDays == other.claimedDays &&
          claimDates == other.claimDates;
}

class VipProductDto {
  final String? productType;
  final String? businessType;
  final bool active;
  final bool paid;
  final bool yearly;
  final String? vipEndTime;
  final String? paidExpireTime;

  const VipProductDto({
    this.productType,
    this.businessType,
    required this.active,
    required this.paid,
    required this.yearly,
    this.vipEndTime,
    this.paidExpireTime,
  });

  @override
  int get hashCode =>
      productType.hashCode ^
      businessType.hashCode ^
      active.hashCode ^
      paid.hashCode ^
      yearly.hashCode ^
      vipEndTime.hashCode ^
      paidExpireTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VipProductDto &&
          runtimeType == other.runtimeType &&
          productType == other.productType &&
          businessType == other.businessType &&
          active == other.active &&
          paid == other.paid &&
          yearly == other.yearly &&
          vipEndTime == other.vipEndTime &&
          paidExpireTime == other.paidExpireTime;
}

class VipUpgradeResultDto {
  final int? statusCode;
  final String? message;
  final String? endTime;

  const VipUpgradeResultDto({this.statusCode, this.message, this.endTime});

  @override
  int get hashCode => statusCode.hashCode ^ message.hashCode ^ endTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VipUpgradeResultDto &&
          runtimeType == other.runtimeType &&
          statusCode == other.statusCode &&
          message == other.message &&
          endTime == other.endTime;
}
